// ============================================================
// content.js — all phase + question data.
//
// Pure data, no logic. Each phase has an intro lesson and a list
// of questions. Each question has a `type` ('MC' or 'BINARY')
// that the engine uses to pick the right question-type module.
//
// Adding a new question type later (e.g. 'CIRCUIT') means adding
// questions with that type here + a matching module under
// js/questions/ — nothing in the engine needs to change.
// ============================================================

export const PHASES = [

  // ── PHASE 1: BINARY BASICS (FREE) ───────────────────────
  {
    id: 1, name: 'BINARY BASICS', sub: 'The language of all computers',
    color: '#2563EB', visual: 'canvas', circuit: 'binary',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'Computers store everything as <strong>binary</strong> — sequences of 1s and 0s called <strong>bits</strong>. Each position has a place value that doubles as you move right: <strong>1, 2, 4, 8, 16...</strong> To convert binary to denary (decimal), add up the place values where the bit is 1.',
      how: 'This is tested in <strong>every single GCSE Computer Science paper</strong> across AQA, OCR, and Eduqas. Expect to convert between binary, denary, and hexadecimal under exam conditions.',
      examples: [
        '🔢 Binary <strong>1010</strong> → place values 1,2,4,8 → 0×1 + 1×2 + 0×4 + 1×8 = <strong>10 in denary</strong>',
        '🔢 Denary <strong>13</strong> → 1×1 + 0×2 + 1×4 + 1×8 → binary <strong>1011</strong>',
        '📝 <strong>GCSE exam tip:</strong> Always write out the place value row (1,2,4,8) above your answer — examiners award marks for working.',
      ],
      tip: '💡 Place values go LEFT to RIGHT: 1, 2, 4, 8. The leftmost bit is the <strong>least significant bit (LSB)</strong>, the rightmost is the <strong>most significant bit (MSB)</strong>.',
      meta: '5 QUESTIONS — BINARY CONVERSION + MULTIPLE CHOICE',
    },
    questions: [
      { type: 'MC', badge: 'BINARY', board: 'AQA · OCR · Eduqas',
        title: 'What is the denary value of binary 1010?',
        desc: 'Place values left→right: 1, 2, 4, 8',
        options: ['10', '5', '12', '8'], answer: '10',
        hints: ['Think: which bits are switched ON (value 1)?', 'Place values are 1, 2, 4, 8. Add up positions where the bit = 1.'],
        explain: '<strong>1010</strong> → 0×1 + 1×2 + 0×4 + 1×8 = 2+8 = <strong>10</strong>. This is a standard AQA/OCR 1-mark conversion question.' },
      { type: 'MC', badge: 'BINARY', board: 'AQA · OCR · Eduqas',
        title: 'How many different values can 8 bits store?',
        desc: 'A group of 8 bits is called a byte',
        options: ['256', '128', '8', '512'], answer: '256',
        hints: ['8 bits means 2 to the power of...', '2⁸ = ?'],
        explain: '<strong>8 bits = 2⁸ = 256 values</strong> (0–255). This is why colour channels go from 0 to 255, and why ASCII fits in one byte. Expect this on Paper 1.' },
      { type: 'BINARY', badge: 'BINARY', board: 'AQA · OCR · Eduqas',
        title: 'Convert denary 6 to 4-bit binary',
        desc: 'Enter the 4-bit binary. Place values: 1, 2, 4, 8',
        bits: 4, answer: [0, 1, 1, 0],
        hints: ['6 = 2 + 4. Which place value bits cover 2 and 4?', 'Bit at position 2 (value 2) = ON. Bit at position 3 (value 4) = ON.'],
        explain: '<strong>6 = 2+4</strong> → bit 1 (value 2) ON, bit 2 (value 4) ON → <strong>0110</strong>. Check: 0×1 + 1×2 + 1×4 + 0×8 = 6 ✓' },
      { type: 'MC', badge: 'BINARY', board: 'AQA · OCR · Eduqas',
        title: 'What is the denary value of binary 1111?',
        desc: 'All four bits are switched ON',
        options: ['15', '16', '8', '14'], answer: '15',
        hints: ['Add up ALL four place values.', '1+2+4+8 = ?'],
        explain: '<strong>1111</strong> = 1+2+4+8 = <strong>15</strong>. The maximum value of 4 bits is always 2⁴−1 = 15. For 8 bits it\'s 255.' },
      { type: 'BINARY', badge: 'BINARY', board: 'AQA · OCR · Eduqas',
        title: 'Convert denary 13 to 4-bit binary',
        desc: 'Enter the 4-bit binary. Place values: 1, 2, 4, 8',
        bits: 4, answer: [1, 0, 1, 1],
        hints: ['13 = 1 + 4 + 8. Can you identify those place value positions?', 'Positions 1 (value 1), 3 (value 4), and 4 (value 8) should be ON.'],
        explain: '<strong>13 = 1+4+8</strong> → bits at values 1, 4, 8 ON → <strong>1011</strong>. Check: 1×1+0×2+1×4+1×8 = 13 ✓' },
    ]
  },

  // ── PHASE 2: LOGIC GATES (FREE) ─────────────────────────
  {
    id: 2, name: 'LOGIC GATES', sub: 'The decision-makers inside every CPU',
    color: '#7C3AED', visual: 'canvas', circuit: 'gate',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: '<strong>Logic gates</strong> process binary signals using boolean logic. They are the fundamental building blocks of all digital circuits. Your CPU contains billions of them. GCSE exams test you on gate symbols, truth tables, and simple circuit outputs.',
      how: 'You must know the four main gates: <strong>AND, OR, NOT, XOR</strong>. For each, know the symbol, the rule, and be able to complete a truth table. AQA and OCR both include logic gate diagrams in Paper 1.',
      examples: [
        '🔵 <strong>AND:</strong> Output = 1 only when BOTH inputs are 1 &nbsp;|&nbsp; (like a strict condition: A AND B must be true)',
        '🟢 <strong>OR:</strong> Output = 1 when AT LEAST ONE input is 1 &nbsp;|&nbsp; (generous: either A OR B is enough)',
        '🔴 <strong>NOT:</strong> Inverts the input &nbsp;|&nbsp; NOT 1 = 0, NOT 0 = 1',
        '🟡 <strong>XOR:</strong> Output = 1 only when inputs are DIFFERENT &nbsp;|&nbsp; 1 XOR 0 = 1, 1 XOR 1 = 0',
      ],
      tip: '💡 Exam trick: NAND = NOT AND (inverted AND). You can build ANY logic circuit from NAND gates alone — this appears in higher-tier questions.',
      meta: '7 QUESTIONS — TRUTH TABLES + BUILD-A-CIRCUIT',
    },
    questions: [
      { type: 'MC', badge: 'LOGIC GATE', board: 'AQA · OCR · Eduqas',
        title: 'AND gate: A = 1, B = 1. What is the output?',
        desc: 'The AND gate is like a series circuit — both switches must be ON',
        options: ['1', '0', 'Undefined', 'Error'], answer: '1',
        hints: ['AND requires BOTH inputs to be 1.', '1 AND 1 = ?'],
        explain: '<strong>AND gate: 1 AND 1 = 1.</strong> The output is 1 only when both inputs are 1. This appears on every major GCSE board\'s Paper 1.' },
      { type: 'MC', badge: 'LOGIC GATE', board: 'AQA · OCR · Eduqas',
        title: 'AND gate: A = 1, B = 0. What is the output?',
        desc: 'Remember: AND needs BOTH inputs to be 1',
        options: ['0', '1', 'Same as A', 'Error'], answer: '0',
        hints: ['AND is strict — if ANY input is 0, the output is 0.', '1 AND 0 = ?'],
        explain: '<strong>AND gate: 1 AND 0 = 0.</strong> Even one input being 0 makes the output 0. Think of it as two switches in series — if one is off, no current flows.' },
      { type: 'MC', badge: 'LOGIC GATE', board: 'AQA · OCR · Eduqas',
        title: 'OR gate: A = 0, B = 0. What is the output?',
        desc: 'OR gate outputs 1 when at least one input is 1',
        options: ['0', '1', 'Undefined', 'Same as A'], answer: '0',
        hints: ['OR only outputs 0 when BOTH inputs are 0.', '0 OR 0 = ?'],
        explain: '<strong>OR gate: 0 OR 0 = 0.</strong> The only way to get 0 from an OR gate is if both inputs are 0. This is the one case students often forget.' },
      { type: 'MC', badge: 'LOGIC GATE', board: 'AQA · OCR · Eduqas',
        title: 'NOT gate: Input = 1. What is the output?',
        desc: 'The NOT gate (inverter) flips the input',
        options: ['0', '1', '2', 'Same'], answer: '0',
        hints: ['NOT simply flips the bit.', 'NOT 1 = ?'],
        explain: '<strong>NOT 1 = 0.</strong> The NOT gate inverts the signal. NOT 0 = 1. It\'s used to reverse conditions and build NAND/NOR gates. Sometimes drawn with a bubble (◯) at the output.' },
      { type: 'MC', badge: 'LOGIC GATE', board: 'AQA · OCR · Eduqas',
        title: 'XOR gate: A = 1, B = 1. What is the output?',
        desc: 'XOR = Exclusive OR — outputs 1 only when inputs are DIFFERENT',
        options: ['0', '1', 'Error', 'Same as OR'], answer: '0',
        hints: ['XOR is "exclusive" — it excludes the case where both are 1.', '1 XOR 1 = ? (are they different?)'],
        explain: '<strong>XOR: 1 XOR 1 = 0.</strong> Inputs are the SAME, so XOR outputs 0. XOR outputs 1 only when inputs differ. Used in binary addition and encryption algorithms.' },
      { type: 'CIRCUIT', badge: 'BUILD CIRCUIT', board: 'AQA · OCR · Eduqas',
        title: 'Drag a gate into the slot so the output is 1.',
        desc: 'Inputs A = 1 and B = 1 feed one gate. Choose a gate that makes the output 1 — more than one works.',
        inputs: [{ id: 'A', value: 1 }, { id: 'B', value: 1 }],
        gates: [{ id: 'G1', in: ['A', 'B'] }],
        output: 'G1', target: 1, palette: ['AND', 'OR', 'XOR'],
        hints: ['With A = 1 and B = 1, which gates give 1?', 'AND(1,1) = 1 and OR(1,1) = 1, but XOR(1,1) = 0.'],
        explain: '<strong>Both AND and OR work here.</strong> AND(1,1)=1 and OR(1,1)=1, so either is a valid answer. XOR(1,1)=0 because the inputs are the same. A circuit can have more than one correct arrangement.' },
      { type: 'CIRCUIT', badge: 'BUILD CIRCUIT', board: 'AQA · OCR · Eduqas',
        title: 'Build a two-gate circuit so the final output is 1.',
        desc: 'Inputs A = 1, B = 0, C = 1. Gate 1 takes A and B; Gate 2 takes Gate 1’s output and C. Make the output 1.',
        inputs: [{ id: 'A', value: 1 }, { id: 'B', value: 0 }, { id: 'C', value: 1 }],
        gates: [{ id: 'G1', in: ['A', 'B'] }, { id: 'G2', in: ['G1', 'C'] }],
        output: 'G2', target: 1, palette: ['AND', 'OR', 'XOR'],
        hints: ['Work left to right: first decide Gate 1’s output from A = 1, B = 0.', 'e.g. OR(1,0) = 1, then AND(1, C=1) = 1. Other combinations also reach 1.'],
        explain: '<strong>One solution: Gate 1 = OR (1 OR 0 = 1), Gate 2 = AND (1 AND 1 = 1).</strong> Several other gate pairs also produce 1 — the simulator accepts any arrangement that hits the target. This is how real circuits chain gates together.' },
    ]
  },

  // ── PHASE 3: HEXADECIMAL (FREE) ─────────────────────────
  {
    id: 3, name: 'HEXADECIMAL', sub: 'Base 16 — the programmer\'s shorthand',
    color: '#059669', visual: 'canvas', circuit: 'binary',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: '<strong>Hexadecimal (hex)</strong> is base 16. It uses digits 0–9 then A–F (where A=10, B=11, C=12, D=13, E=14, F=15). One hex digit represents exactly 4 binary bits, making it a compact way to represent binary. GCSE exams expect you to convert between hex, binary, and denary.',
      how: 'Hex appears everywhere in computing: memory addresses (<code>0xFF3A</code>), colour codes (<code>#FF8800</code>), error codes. The <code>0x</code> prefix means "this number is hexadecimal".',
      examples: [
        '🔢 Hex <strong>A</strong> = 10 in denary &nbsp;|&nbsp; Hex <strong>F</strong> = 15 in denary',
        '🔢 Hex <strong>1F</strong> = 1×16 + 15×1 = <strong>31</strong> in denary',
        '🔢 Hex <strong>FF</strong> = 15×16 + 15×1 = <strong>255</strong> in denary (maximum value of one byte)',
        '📝 <strong>GCSE exam tip:</strong> Binary → Hex: split binary into groups of 4 bits, convert each group. e.g. 11110000 → 1111=F, 0000=0 → <strong>F0</strong>',
      ],
      tip: '💡 FF in hex = 255 in denary = 11111111 in binary. One byte always = 2 hex digits. Learn this — it comes up in almost every paper.',
      meta: '5 QUESTIONS — HEX CONVERSION + MULTIPLE CHOICE',
    },
    questions: [
      { type: 'MC', badge: 'HEX', board: 'AQA · OCR · Eduqas',
        title: 'What is the denary value of hex A?',
        desc: 'Hex uses letters A–F for values 10–15',
        options: ['10', '11', '16', '15'], answer: '10',
        hints: ['Hex A is the first letter — it comes right after 9.', 'A=10, B=11, C=12, D=13, E=14, F=15'],
        explain: '<strong>Hex A = 10 in denary.</strong> After the digit 9, hex continues with A=10 through to F=15. This is why 16 is the "base" — you need 16 symbols.' },
      { type: 'MC', badge: 'HEX', board: 'AQA · OCR · Eduqas',
        title: 'What is the denary value of hex FF?',
        desc: 'FF is the maximum value of a single byte (8 bits)',
        options: ['255', '256', '128', '240'], answer: '255',
        hints: ['Each hex digit F = 15. Place values in hex: 1, 16, 256...', 'F×16 + F×1 = ?'],
        explain: '<strong>Hex FF = 15×16 + 15×1 = 240+15 = 255.</strong> This is why colour channels max at 255, passwords hash to FF, and byte values stop at 255. Know this cold.' },
      { type: 'MC', badge: 'HEX', board: 'AQA · OCR · Eduqas',
        title: 'Convert binary 11110000 to hexadecimal',
        desc: 'Split into groups of 4 bits and convert each group',
        options: ['F0', 'FF', '0F', 'E0'], answer: 'F0',
        hints: ['Split into two groups of 4: 1111 and 0000', '1111 in binary = 15 in denary = F in hex. 0000 = 0.'],
        explain: '<strong>11110000 → 1111|0000 → F|0 → F0.</strong> This is the standard GCSE method: split binary into nibbles (4-bit groups), convert each to a hex digit.' },
      { type: 'MC', badge: 'HEX', board: 'AQA · OCR · Eduqas',
        title: 'Why do programmers use hexadecimal?',
        desc: 'Think about the relationship between hex and binary',
        options: ['One hex digit represents exactly 4 binary bits', 'It is easier to type than binary', 'Computers process hex faster', 'It uses less storage than binary'], answer: 'One hex digit represents exactly 4 binary bits',
        hints: ['How many values can 4 bits hold? How many values does one hex digit hold?', 'Both have exactly 16 possible values (0–15 / 0–F).'],
        explain: '<strong>1 hex digit = 4 bits = 16 values.</strong> This perfect correspondence means hex is a compact, human-readable shorthand for binary. FF is far easier to read than 11111111.' },
      { type: 'MC', badge: 'HEX', board: 'AQA · OCR · Eduqas',
        title: 'What is hex 2B in denary?',
        desc: 'Place values in hex: units=1, sixteens=16',
        options: ['43', '33', '35', '27'], answer: '43',
        hints: ['2B: the 2 is worth 2×16. B = 11 in denary.', '2×16 + 11×1 = ?'],
        explain: '<strong>Hex 2B = 2×16 + B(11)×1 = 32+11 = 43.</strong> Standard two-digit hex conversion — a very common exam question format on AQA Paper 2.' },
    ]
  },

  // ── PHASE 4: HEX COLOURS (FREE) ─────────────────────────
  {
    id: 4, name: 'HEX COLOURS', sub: 'How screens mix red, green, and blue light',
    color: '#DC2626', visual: 'swatch', circuit: null,
    boards: ['AQA', 'OCR'],
    intro: {
      what: 'Every colour on a screen is made by mixing <strong>Red, Green, and Blue (RGB)</strong> light. Each channel is stored as one byte (0–255), written as two hex digits. A full hex colour code like <code>#FF8800</code> contains 3 bytes: FF=red, 88=green, 00=blue.',
      how: 'The format is always <strong>#RRGGBB</strong>. 00 means that channel is off, FF means it\'s at maximum. Mixing all three channels at maximum gives white; all at 00 gives black.',
      examples: [
        '🔴 <code>#FF0000</code> → Red=255, Green=0, Blue=0 → <strong>pure red</strong>',
        '🟢 <code>#00FF00</code> → Red=0, Green=255, Blue=0 → <strong>pure green</strong>',
        '⚪ <code>#FFFFFF</code> → all channels at 255 → <strong>white</strong>',
        '⚫ <code>#000000</code> → all channels at 0 → <strong>black</strong>',
      ],
      tip: '💡 Red+Green light = Yellow (not brown — screens mix light, not paint!). Red+Blue = Magenta. Green+Blue = Cyan.',
      meta: '5 QUESTIONS — COLOUR IDENTIFICATION + HEX READING',
    },
    questions: [
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'What colour does #FF0000 represent?',
        desc: 'Format: #RRGGBB — Red, Green, Blue',
        options: ['Red', 'Green', 'Blue', 'White'], answer: 'Red',
        hints: ['The first two digits (FF) are the red channel.', 'Red=FF (255), Green=00, Blue=00 — only red is on.'],
        explain: '<strong>#FF0000: Red=FF(255), Green=00, Blue=00.</strong> Only the red channel is at maximum. This is pure red light.' },
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'What colour does #FFFF00 represent?',
        desc: 'Red and green channels are both at maximum',
        options: ['Yellow', 'Cyan', 'Purple', 'White'], answer: 'Yellow',
        hints: ['Red=FF, Green=FF, Blue=00. What do red and green light make?', 'On screens, red + green light = yellow (opposite to paint mixing).'],
        explain: '<strong>#FFFF00: Red=FF, Green=FF, Blue=00 → Yellow.</strong> This surprises many students — mixing red and green LIGHT gives yellow, not brown. Screens use additive colour mixing.' },
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'Which hex code produces pure blue?',
        desc: 'Only the blue channel should be at maximum (FF)',
        options: ['#0000FF', '#FF0000', '#00FF00', '#00FFFF'], answer: '#0000FF',
        hints: ['Format is #RRGGBB. Blue is the last two digits.', 'Red=00, Green=00, Blue=FF.'],
        explain: '<strong>#0000FF: Red=00, Green=00, Blue=FF(255).</strong> Only the blue channel is active. This is pure blue — commonly used for hyperlinks and UI elements.' },
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'How many different colours can be represented using #RRGGBB?',
        desc: 'Each channel is one byte (0–255)',
        options: ['16,777,216', '65,536', '256', '16,384'], answer: '16,777,216',
        hints: ['There are 3 channels, each with 256 possible values.', '256 × 256 × 256 = ?'],
        explain: '<strong>256 × 256 × 256 = 16,777,216</strong> (about 16.7 million) colours. This is called 24-bit colour (3 bytes = 24 bits). Higher-quality images use 32-bit (adds an alpha/transparency channel).' },
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'What does #000000 represent?',
        desc: 'All three channels are set to zero',
        options: ['Black', 'White', 'Grey', 'Transparent'], answer: 'Black',
        hints: ['00 means the channel is completely OFF.', 'If all three light channels are off, what colour do you see?'],
        explain: '<strong>#000000 → Black.</strong> All channels at 0 means no light. Screens are black when pixels are off. Contrast with #FFFFFF (white) where all channels are at maximum.' },
    ]
  },

  // ── PHASE 5: NETWORKING (PREMIUM) ───────────────────────
  {
    id: 5, name: 'NETWORKING', sub: 'How computers communicate across the world',
    color: '#0891B2', visual: 'canvas', circuit: 'cpu',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'Networks allow computers to share data. The internet is a global network using <strong>TCP/IP</strong> protocols. Every device has a unique <strong>IP address</strong>, and <strong>DNS</strong> converts human-readable names into IP addresses. Data travels as <strong>packets</strong> routed by devices called <strong>routers</strong>.',
      how: 'GCSE networking questions test: network types (LAN/WAN), network topologies, protocols (HTTP, HTTPS, FTP, TCP, IP, DNS, SMTP), hardware (router, switch, NIC), and network security.',
      examples: [
        '📡 <strong>LAN</strong> (Local Area Network): Devices in one location e.g. school network',
        '🌐 <strong>WAN</strong> (Wide Area Network): Spans large geographic areas e.g. the internet',
        '📖 <strong>DNS:</strong> You type <code>bbc.co.uk</code> → DNS looks up → <code>151.101.0.81</code> → your browser connects',
        '📦 <strong>Packet:</strong> Data split into chunks with source/destination IP headers — like addressed envelopes',
      ],
      tip: '💡 Exam favourite: know the difference between a <strong>router</strong> (connects networks, uses IP addresses) and a <strong>switch</strong> (connects devices within a network, uses MAC addresses).',
      meta: '7 QUESTIONS — PACKET ROUTING + PROTOCOLS',
    },
    questions: [
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What does DNS stand for?',
        desc: 'DNS is described as the "phonebook of the internet"',
        options: ['Domain Name System', 'Data Network Server', 'Digital Node Switch', 'Direct Name Service'], answer: 'Domain Name System',
        hints: ['It converts website names into something computers understand.', 'Think: what does a phonebook do? DNS does the same for websites.'],
        explain: '<strong>DNS = Domain Name System.</strong> It translates domain names (bbc.co.uk) into IP addresses (151.101.0.81). Without DNS you\'d memorise IP addresses. This is a guaranteed 1-mark question on most papers.' },
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What is the difference between a LAN and a WAN?',
        desc: 'Two fundamental network types you must know',
        options: ['LAN covers a small area; WAN spans large geographic areas', 'LAN is wireless; WAN is wired', 'LAN uses TCP; WAN uses IP', 'LAN is faster than WAN always'], answer: 'LAN covers a small area; WAN spans large geographic areas',
        hints: ['LAN = Local Area Network. Where is "local"?', 'Think school vs the internet.'],
        explain: '<strong>LAN (Local Area Network)</strong> connects devices in one location (school, office). <strong>WAN (Wide Area Network)</strong> spans large areas — the internet is the largest WAN. A key 2-mark question on all boards.' },
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What is the role of a router?',
        desc: 'Routers are the traffic directors of the internet',
        options: ['Directs packets between different networks using IP addresses', 'Connects devices within a single network', 'Converts domain names to IP addresses', 'Encrypts data before transmission'], answer: 'Directs packets between different networks using IP addresses',
        hints: ['A router works with IP addresses and connects different networks together.', 'Compare: a switch connects devices WITHIN a network; a router connects NETWORKS to each other.'],
        explain: '<strong>Routers</strong> forward data packets between networks using IP addresses. Your home router connects your LAN to the internet (a WAN). Examiners often ask you to distinguish routers from switches.' },
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What does HTTP stand for?',
        desc: 'You see this protocol at the start of web addresses',
        options: ['HyperText Transfer Protocol', 'High Traffic Transfer Process', 'Home Terminal Text Program', 'Hyperlink Transport Tool Protocol'], answer: 'HyperText Transfer Protocol',
        hints: ['It\'s the protocol used to transfer web pages between servers and browsers.', 'The S in HTTPS stands for Secure — it adds encryption via TLS.'],
        explain: '<strong>HTTP = HyperText Transfer Protocol.</strong> The set of rules for transferring web pages. HTTPS adds TLS encryption (the padlock icon). Knowing common protocols (HTTP, FTP, SMTP, DNS) is essential for Paper 1.' },
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What is packet switching?',
        desc: 'The method used to transmit data across the internet',
        options: ['Breaking data into packets that travel independently and are reassembled at destination', 'Sending all data in one continuous stream', 'Encrypting data before transmission', 'Compressing files before sending'], answer: 'Breaking data into packets that travel independently and are reassembled at destination',
        hints: ['Think of sending a book torn into individual pages — each page finds its own route.', 'Packets can take different routes and arrive out of order, then be reassembled.'],
        explain: '<strong>Packet switching</strong> splits data into packets, each with header information (source/destination IP). Packets travel independently across the network and are reassembled. It\'s efficient because network capacity is shared.' },
      { type: 'PACKET', badge: 'PACKET SWITCHING', board: 'AQA · OCR · Eduqas',
        title: 'Route the packet from HOME to the SERVER.',
        desc: 'Click a connected router to hop the packet. One link is down (dashed red) — route around it before the hop budget runs out.',
        nodes: [
          { id: 'HOME', x: 0.10, y: 160, label: 'HOME' },
          { id: 'R1', x: 0.38, y: 80, label: 'R1' },
          { id: 'R2', x: 0.38, y: 250, label: 'R2' },
          { id: 'R3', x: 0.66, y: 160, label: 'R3' },
          { id: 'SERVER', x: 0.90, y: 160, label: 'SERVER' },
        ],
        links: [['HOME', 'R1'], ['HOME', 'R2'], ['R1', 'R3'], ['R2', 'R3'], ['R3', 'SERVER'], ['R1', 'SERVER'], ['R2', 'SERVER']],
        down: [['R1', 'SERVER']],
        source: 'HOME', dest: 'SERVER', ttl: 3,
        hints: ['The dashed R1–SERVER link is down — a packet cannot cross it.', 'HOME → R2 → SERVER reaches the destination in two hops.'],
        explain: '<strong>Packet switching</strong> routes packets independently and can take different paths. With the R1–SERVER link down, the network routes around the failure (e.g. HOME → R2 → SERVER). The <strong>TTL (time to live)</strong> is a hop limit that stops a lost packet circulating the network forever.' },
      { type: 'PACKET', badge: 'PACKET SWITCHING', board: 'AQA · OCR · Eduqas',
        title: 'Send the packet to the SERVER in as few hops as possible.',
        desc: 'Only 2 hops of TTL. Pick the shortest route — a wrong turn wastes the budget and the packet is dropped.',
        nodes: [
          { id: 'PC', x: 0.10, y: 160, label: 'PC' },
          { id: 'A', x: 0.42, y: 80, label: 'R-A' },
          { id: 'B', x: 0.42, y: 250, label: 'R-B' },
          { id: 'C', x: 0.70, y: 250, label: 'R-C' },
          { id: 'SERVER', x: 0.90, y: 160, label: 'SERVER' },
        ],
        links: [['PC', 'A'], ['PC', 'B'], ['A', 'SERVER'], ['B', 'C'], ['C', 'SERVER']],
        source: 'PC', dest: 'SERVER', ttl: 2,
        hints: ['Two hops only — which neighbour of PC connects straight to a router that reaches the SERVER?', 'PC → R-A → SERVER is two hops; PC → R-B → R-C → SERVER is three (too many).'],
        explain: '<strong>Efficient routing</strong> matters: PC → R-A → SERVER reaches the SERVER in 2 hops, while PC → R-B → R-C → SERVER takes 3. Routers use routing tables to forward each packet along the most efficient available path; the TTL caps how many hops a packet may waste.' },
    ]
  },

  // ── PHASE 6: ALGORITHMS (PREMIUM) ───────────────────────
  {
    id: 6, name: 'ALGORITHMS', sub: 'Sorting, searching, and computational thinking',
    color: '#D97706', visual: 'sort', circuit: null,
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'An <strong>algorithm</strong> is a precise set of steps to solve a problem. GCSE Computer Science tests sorting algorithms (Bubble Sort, Merge Sort, Insertion Sort) and searching algorithms (Linear Search, Binary Search). You must trace through them step-by-step.',
      how: '<strong>Big O notation</strong> describes efficiency. O(n) = linear time, O(n²) = quadratic, O(log n) = logarithmic. Binary search (O(log n)) is much faster than linear search (O(n)) for large sorted datasets.',
      examples: [
        '🔄 <strong>Bubble Sort pass on [5,3,1,4]:</strong> Compare 5&3 → swap → [3,5,1,4] → compare 5&1 → swap → [3,1,5,4] → compare 5&4 → swap → [3,1,4,5]',
        '🔍 <strong>Binary Search for 7 in [1,3,5,7,9]:</strong> Check middle (5) → 7>5, look right → check (7) → found in 2 steps!',
        '📝 <strong>Exam tip:</strong> Bubble Sort needs n-1 passes for n items. Show ALL comparisons and swaps — each earns a mark.',
      ],
      tip: '💡 Binary Search requires the list to be <strong>sorted first</strong>. Linear Search works on unsorted lists but is slower. This distinction is a common exam trap.',
      meta: '7 QUESTIONS — BUBBLE-SORT TRACE + EFFICIENCY',
    },
    questions: [
      { type: 'MC', badge: 'ALGORITHM', board: 'AQA · OCR · Eduqas',
        title: 'After one pass of Bubble Sort on [4, 2, 7, 1], what is the result?',
        desc: 'Bubble Sort compares adjacent pairs and swaps if out of order',
        options: ['[2, 4, 1, 7]', '[1, 2, 4, 7]', '[4, 2, 1, 7]', '[2, 1, 4, 7]'], answer: '[2, 4, 1, 7]',
        hints: ['Start at the left. Compare 4 and 2 — are they in order?', '4>2 so swap → [2,4,7,1]. Then compare 4 and 7 — no swap. Then 7 and 1 — swap.'],
        explain: '<strong>Pass 1:</strong> 4>2 swap→[2,4,7,1] → 4<7 no swap → 7>1 swap→[2,4,1,7]. The largest value (7) "bubbles" to the end. One full pass per exam mark — show all comparisons.' },
      { type: 'TRACE', badge: 'TRACE', board: 'AQA · OCR · Eduqas', algo: 'bubble',
        title: 'Trace one pass of Bubble Sort on [5, 3, 8, 1].',
        desc: 'Work left to right. At each highlighted pair, choose SWAP if the left value is larger, otherwise KEEP.',
        array: [5, 3, 8, 1],
        hints: ['Bubble Sort compares adjacent pairs and swaps only when the left value is bigger.', 'First pair 5 & 3: 5 > 3, so swap. Then 5 & 8: keep. Then 8 & 1: swap.'],
        explain: '<strong>One pass — swap, keep, swap → [3, 5, 1, 8].</strong> 5>3 swap→[3,5,8,1]; 5<8 keep; 8>1 swap→[3,5,1,8]. The largest value (8) bubbles to the end. Every comparison earns a mark in the exam — always show them all.' },
      { type: 'TRACE', badge: 'TRACE', board: 'AQA · OCR · Eduqas', algo: 'bubble',
        title: 'Trace one pass of Bubble Sort on [4, 1, 6, 2, 7].',
        desc: 'Four comparisons, left to right. SWAP when the left value is larger, otherwise KEEP.',
        array: [4, 1, 6, 2, 7],
        hints: ['Only swap when the left number is bigger than the one to its right.', '4 & 1: swap; 4 & 6: keep; 6 & 2: swap; 6 & 7: keep.'],
        explain: '<strong>One pass — swap, keep, swap, keep → [1, 4, 2, 6, 7].</strong> 4>1 swap→[1,4,6,2,7]; 4<6 keep; 6>2 swap→[1,4,2,6,7]; 6<7 keep. Here 7 was already at the end, so it stays put.' },
      { type: 'MC', badge: 'ALGORITHM', board: 'AQA · OCR · Eduqas',
        title: 'Binary Search: finding 9 in [1, 3, 5, 7, 9, 11]. Which element is checked first?',
        desc: 'Binary Search always starts at the middle element',
        options: ['5', '7', '1', '9'], answer: '5',
        hints: ['Binary Search picks the middle element of the list first.', 'List has 6 items. Middle index = 6÷2 = item at position 3 (value 5, using 0-based) or position 3 (value 5 or 7 depending on convention).'],
        explain: '<strong>Binary Search</strong> starts at the middle: index 2 (0-based) = value 5. Since 9>5, search the right half [7,9,11]. Next check: 9. Found! Only 2 checks instead of 6 with linear search.' },
      { type: 'MC', badge: 'ALGORITHM', board: 'AQA · OCR · Eduqas',
        title: 'What is the time complexity of Binary Search?',
        desc: 'Big O notation describes how time grows with input size',
        options: ['O(log n)', 'O(n)', 'O(n²)', 'O(1)'], answer: 'O(log n)',
        hints: ['Binary Search halves the remaining items each step.', 'Doubling the list size only adds ONE more step to Binary Search.'],
        explain: '<strong>Binary Search = O(log n).</strong> Each step halves the search space. For 1 million items, it takes at most 20 steps. Linear search O(n) would take up to 1 million. This efficiency difference is a key exam concept.' },
      { type: 'MC', badge: 'ALGORITHM', board: 'AQA · OCR · Eduqas',
        title: 'Which sorting algorithm has O(n²) worst-case time complexity?',
        desc: 'Think about how many comparisons are made for n items',
        options: ['Bubble Sort', 'Binary Search', 'Merge Sort', 'Linear Search'], answer: 'Bubble Sort',
        hints: ['For n items, Bubble Sort does roughly n×n comparisons in the worst case.', 'Merge Sort is more efficient — it\'s O(n log n).'],
        explain: '<strong>Bubble Sort = O(n²).</strong> For 10 items: up to 100 comparisons. For 100 items: up to 10,000. This makes it impractical for large datasets. Merge Sort (O(n log n)) is much faster but harder to trace.' },
      { type: 'MC', badge: 'ALGORITHM', board: 'AQA · OCR · Eduqas',
        title: 'What is a key requirement for Binary Search to work?',
        desc: 'A precondition that must be true before the algorithm can run',
        options: ['The list must be sorted', 'The list must have an even number of items', 'All items must be unique', 'The list must contain numbers only'], answer: 'The list must be sorted',
        hints: ['Binary Search works by comparing target to the middle and going left or right. What assumption makes this work?', 'If the list is unsorted, going "right" when the target is larger doesn\'t guarantee anything.'],
        explain: '<strong>Binary Search requires a sorted list.</strong> Without sorting, you can\'t determine which half contains the target. This is a classic exam trap — students forget this precondition.' },
    ]
  },

  // ── PHASE 7: ENCRYPTION & SECURITY (PREMIUM) ────────────
  {
    id: 7, name: 'ENCRYPTION', sub: 'Keeping data safe in a connected world',
    color: '#BE185D', visual: 'canvas', circuit: 'cpu',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: '<strong>Encryption</strong> scrambles data so only the intended recipient can read it. GCSE Computer Science covers Caesar cipher, symmetric vs asymmetric encryption, and common cyber threats (malware, phishing, SQL injection).',
      how: 'Key exam topics: <strong>Caesar cipher</strong> (shift letters by a fixed amount), <strong>symmetric encryption</strong> (same key to encrypt and decrypt), <strong>asymmetric encryption</strong> (public key encrypts, private key decrypts), and why HTTPS uses both.',
      examples: [
        '🔑 <strong>Caesar cipher (shift 3):</strong> A→D, B→E, C→F. "CAT" → "FDW"',
        '🔒 <strong>Symmetric:</strong> One shared secret key — fast but key must be shared securely',
        '🗝️ <strong>Asymmetric:</strong> Public key (share freely) encrypts; Private key (keep secret) decrypts',
        '📝 <strong>Exam tip:</strong> HTTPS uses asymmetric encryption to share a symmetric key, then uses that symmetric key for the session (it\'s faster).',
      ],
      tip: '💡 Common threats: <strong>Malware</strong> (virus, ransomware, spyware), <strong>Phishing</strong> (fake emails tricking users), <strong>SQL injection</strong> (malicious database queries), <strong>DDoS</strong> (flooding a server to take it offline).',
      meta: '7 QUESTIONS — CIPHER WHEEL + CYBER SECURITY',
    },
    questions: [
      { type: 'MC', badge: 'ENCRYPTION', board: 'AQA · OCR · Eduqas',
        title: 'Caesar cipher with shift 3: what does the letter "H" become?',
        desc: 'Shift each letter forward by 3 positions in the alphabet',
        options: ['K', 'J', 'G', 'I'], answer: 'K',
        hints: ['Count 3 places forward from H: H→I→J→K', 'Shift of 3 means add 3 to the letter\'s position.'],
        explain: '<strong>H + 3 = K.</strong> Caesar cipher shifts each letter by a fixed amount. Julius Caesar used shift 3 for military messages. It\'s trivially broken today (only 25 possible keys) but teaches substitution cipher principles.' },
      { type: 'CIPHER', badge: 'CIPHER WHEEL', board: 'AQA · OCR · Eduqas',
        title: 'Turn the wheel to decode the message FDW.',
        desc: 'It was encrypted with a Caesar shift of 3. Rotate the wheel until the decoded row spells a word, then decode.',
        mode: 'decode', text: 'FDW', shift: 3, answer: 'CAT',
        hints: ['Shift 3 means every letter moved 3 places forward when encrypted — turn it back by 3.', 'F→C, D→A, W→T spells a three-letter animal.'],
        explain: '<strong>FDW shifted back by 3 = CAT.</strong> Decoding reverses the shift: F→C, D→A, W→T. This is the lesson\'s own example (CAT → FDW) run backwards.' },
      { type: 'CIPHER', badge: 'CIPHER WHEEL', board: 'AQA · OCR · Eduqas',
        title: 'Crack the code: turn the wheel until MJQQT reads as a word.',
        desc: 'The shift is unknown. Try shifts until the message makes sense — that is exactly how a Caesar cipher is broken (only 25 keys to test).',
        mode: 'decode', text: 'MJQQT', shift: 5, answer: 'HELLO',
        hints: ['There are only 25 possible shifts — work through them one at a time.', 'M→H is a shift of 5; the same shift decodes every letter.'],
        explain: '<strong>MJQQT shifted back by 5 = HELLO.</strong> With only 25 keys, a Caesar cipher falls to brute force — trying each shift until readable text appears. That tiny key space is exactly why real encryption uses enormous keys.' },
      { type: 'MC', badge: 'ENCRYPTION', board: 'AQA · OCR · Eduqas',
        title: 'What is the difference between symmetric and asymmetric encryption?',
        desc: 'Two fundamental types of modern encryption',
        options: ['Symmetric uses one shared key; asymmetric uses a public/private key pair', 'Symmetric is stronger; asymmetric is weaker', 'Symmetric uses more keys; asymmetric uses fewer', 'Symmetric is for files; asymmetric is for emails only'], answer: 'Symmetric uses one shared key; asymmetric uses a public/private key pair',
        hints: ['Symmetric = same key for both sides. Think "symmetrical" — both sides are the same.', 'Asymmetric uses two mathematically linked keys — public (share freely) and private (keep secret).'],
        explain: '<strong>Symmetric:</strong> one shared secret key (fast, used for bulk data). <strong>Asymmetric:</strong> public key encrypts, private key decrypts (slower, used for key exchange). HTTPS uses asymmetric to share a symmetric session key.' },
      { type: 'MC', badge: 'ENCRYPTION', board: 'AQA · OCR · Eduqas',
        title: 'What type of attack involves flooding a server with traffic to make it unavailable?',
        desc: 'This attack aims to deny service to legitimate users',
        options: ['DDoS (Distributed Denial of Service)', 'Phishing', 'SQL Injection', 'Brute Force'], answer: 'DDoS (Distributed Denial of Service)',
        hints: ['The attack "denies" users access to a service by overwhelming it.', 'DDoS = Distributed — it uses many computers (a botnet) to flood the target.'],
        explain: '<strong>DDoS (Distributed Denial of Service)</strong> floods a server with requests from many compromised computers (a botnet) until it crashes or becomes too slow. A common 2-mark exam question: describe the attack and its impact.' },
      { type: 'MC', badge: 'ENCRYPTION', board: 'AQA · OCR · Eduqas',
        title: 'What is phishing?',
        desc: 'One of the most common social engineering attacks',
        options: ['Tricking users into revealing personal data via fake emails or websites', 'Installing malware via USB drives', 'Flooding a network with traffic', 'Intercepting data packets on a network'], answer: 'Tricking users into revealing personal data via fake emails or websites',
        hints: ['It\'s named after "fishing" — dangling bait to trick victims.', 'The attack targets human behaviour, not technical vulnerabilities.'],
        explain: '<strong>Phishing</strong> uses fake emails or websites that mimic legitimate organisations (banks, HMRC) to steal passwords, card numbers, or personal data. It\'s a "social engineering" attack — exploiting human psychology rather than software flaws.' },
      { type: 'MC', badge: 'ENCRYPTION', board: 'AQA · OCR · Eduqas',
        title: 'What is SQL injection?',
        desc: 'A common attack on databases accessed via web forms',
        options: ['Inserting malicious SQL code into input fields to manipulate a database', 'A type of DDoS attack', 'Encrypting a database with ransomware', 'Stealing cookies from a browser'], answer: 'Inserting malicious SQL code into input fields to manipulate a database',
        hints: ['SQL is used to query databases. What if a user typed SQL commands into a login form?', 'Input: "admin\' OR 1=1 --" could bypass a login check entirely.'],
        explain: '<strong>SQL injection</strong> inserts SQL commands into user input fields (e.g. login forms). If input isn\'t sanitised, the database executes the injected command. Prevention: input validation and parameterised queries.' },
    ]
  },

  // ── PHASE 8: CPU & MEMORY (PREMIUM) ─────────────────────
  {
    id: 8, name: 'CPU & MEMORY', sub: 'Von Neumann architecture and the fetch-decode-execute cycle',
    color: '#4F46E5', visual: 'canvas', circuit: 'cpu',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'The <strong>CPU (Central Processing Unit)</strong> is the brain of a computer. It uses the <strong>fetch-decode-execute cycle</strong> to process instructions. The <strong>von Neumann architecture</strong> stores both programs and data in the same memory — the standard model for all modern computers.',
      how: 'Key components: <strong>ALU</strong> (does maths and logic), <strong>CU</strong> (Control Unit — directs operations), <strong>Registers</strong> (tiny, ultra-fast memory inside the CPU), <strong>Cache</strong> (fast memory near CPU), <strong>RAM</strong> (main memory), <strong>ROM</strong> (read-only, stores BIOS/firmware).',
      examples: [
        '🔁 <strong>Fetch:</strong> CU gets the next instruction from RAM (at address in Program Counter)',
        '🔁 <strong>Decode:</strong> CU interprets the instruction',
        '🔁 <strong>Execute:</strong> ALU or other component carries out the instruction',
        '📝 <strong>CPU performance factors:</strong> Clock speed (GHz), number of cores, cache size',
      ],
      tip: '💡 Exam trap: <strong>RAM is volatile</strong> (lost when power off). <strong>ROM is non-volatile</strong> (persists). RAM is read/write; ROM is read-only. These definitions appear on every paper.',
      meta: '7 QUESTIONS — FETCH-DECODE-EXECUTE + MEMORY',
    },
    questions: [
      { type: 'MC', badge: 'CPU', board: 'AQA · OCR · Eduqas',
        title: 'What does the ALU do?',
        desc: 'ALU is a key component of the CPU',
        options: ['Performs arithmetic and logical operations', 'Stores data permanently', 'Fetches instructions from memory', 'Connects the CPU to external devices'], answer: 'Performs arithmetic and logical operations',
        hints: ['ALU = Arithmetic Logic Unit. The clue is in the name.', 'It handles: addition, subtraction, comparisons, AND, OR, NOT operations.'],
        explain: '<strong>ALU (Arithmetic Logic Unit)</strong> performs all maths (add, subtract, multiply) and logic operations (AND, OR, NOT, compare). It\'s built from the logic gates in Phase 2. Every calculation in every program goes through the ALU.' },
      { type: 'MC', badge: 'CPU', board: 'AQA · OCR · Eduqas',
        title: 'What is the fetch-decode-execute cycle?',
        desc: 'The fundamental repeating process of every CPU',
        options: ['Fetch instruction from memory, decode it, execute it — repeated continuously', 'Store, compress, and transmit data', 'Read, write, and delete files', 'Boot, load, and run an operating system'], answer: 'Fetch instruction from memory, decode it, execute it — repeated continuously',
        hints: ['Three stages, in order: get the instruction, understand it, carry it out.', 'The Program Counter (PC) register tracks which instruction to fetch next.'],
        explain: '<strong>Fetch-Decode-Execute:</strong> The CPU fetches the instruction at the address in the Program Counter, decodes what operation it means, then executes it. This cycle runs billions of times per second and is tested on every GCSE paper.' },
      { type: 'FDE', badge: 'CPU CYCLE', board: 'AQA · OCR · Eduqas',
        title: 'Trace the fetch–decode–execute cycle through the CPU.',
        desc: 'At each step the source register glows — click the component the data moves to. Follow it from fetch through to execute.',
        steps: [
          { stage: 'FETCH', from: 'PC', answer: 'MAR', prompt: 'The address in the Program Counter is copied to which register?' },
          { stage: 'FETCH', from: 'RAM', answer: 'MDR', prompt: 'The instruction at that address is fetched from RAM into which register?' },
          { stage: 'FETCH', from: 'MDR', answer: 'CIR', prompt: 'The fetched instruction is copied from the MDR into which register?' },
          { stage: 'FETCH', from: 'PC', answer: 'PC', prompt: 'Which register is then incremented to point at the next instruction?', note: 'PC + 1' },
          { stage: 'DECODE', from: 'CIR', answer: 'CU', prompt: 'Which unit decodes the instruction held in the CIR?' },
          { stage: 'EXECUTE', from: 'CU', answer: 'ALU', prompt: 'Which unit carries out an arithmetic or logic instruction?' },
        ],
        hints: ['Fetch order: PC → MAR, then the instruction returns into the MDR, then into the CIR.', 'After fetching, the PC is incremented; then the CU decodes and the ALU executes.'],
        explain: '<strong>Fetch:</strong> PC→MAR, RAM→MDR, MDR→CIR, then PC is incremented. <strong>Decode:</strong> the Control Unit interprets the instruction in the CIR. <strong>Execute:</strong> the ALU carries out arithmetic/logic. This cycle repeats billions of times a second — being able to trace it earns marks on every board.' },
      { type: 'FDE', badge: 'CPU CYCLE', board: 'AQA · OCR · Eduqas',
        title: 'Trace just the FETCH stage of the cycle.',
        desc: 'Four steps. At each one, click the component the data moves to.',
        steps: [
          { stage: 'FETCH', from: 'PC', answer: 'MAR', prompt: 'The address in the Program Counter goes to which register first?' },
          { stage: 'FETCH', from: 'RAM', answer: 'MDR', prompt: 'The instruction is read from RAM into which register?' },
          { stage: 'FETCH', from: 'MDR', answer: 'CIR', prompt: 'It is then copied from the MDR into which register?' },
          { stage: 'FETCH', from: 'PC', answer: 'PC', prompt: 'Finally, which register is incremented ready for the next instruction?', note: 'PC + 1' },
        ],
        hints: ['The MAR holds the ADDRESS; the MDR holds the DATA/instruction.', 'PC → MAR → (RAM) → MDR → CIR, then increment the PC.'],
        explain: '<strong>Fetch:</strong> the address in the PC is placed in the MAR; the instruction at that address is read from RAM into the MDR; it is copied into the CIR; and the PC is incremented so the next cycle fetches the following instruction.' },
      { type: 'MC', badge: 'MEMORY', board: 'AQA · OCR · Eduqas',
        title: 'What is the key difference between RAM and ROM?',
        desc: 'Both are types of primary storage inside a computer',
        options: ['RAM is volatile (lost when power off); ROM is non-volatile (persists)', 'RAM is faster than ROM', 'RAM stores the OS; ROM stores user files', 'RAM is read-only; ROM is read/write'], answer: 'RAM is volatile (lost when power off); ROM is non-volatile (persists)',
        hints: ['Volatile = data is lost when the power is cut. Which one clears when you turn off your computer?', 'ROM stores the BIOS/firmware that runs when you first switch on — it must survive power loss.'],
        explain: '<strong>RAM = volatile, read/write.</strong> Data is lost when power is removed. Used for running programs. <strong>ROM = non-volatile, read-only.</strong> Stores firmware/BIOS. Persists without power. A classic 2-mark question: state and explain the difference.' },
      { type: 'MC', badge: 'CPU', board: 'AQA · OCR · Eduqas',
        title: 'Which factor does NOT directly affect CPU performance?',
        desc: 'Know what actually determines how fast a CPU runs',
        options: ['The colour of the computer case', 'Clock speed (GHz)', 'Number of cores', 'Cache size'], answer: 'The colour of the computer case',
        hints: ['Think about what physically affects how fast the processor runs.', 'Clock speed, cores, and cache all have a direct technical impact on performance.'],
        explain: '<strong>CPU performance is affected by:</strong> Clock speed (how many cycles per second), Number of cores (parallel processing), Cache size (faster access to frequently used data). The case colour has zero effect — a common "odd one out" question.' },
      { type: 'MC', badge: 'MEMORY', board: 'AQA · OCR · Eduqas',
        title: 'In the memory hierarchy, which type of memory is fastest?',
        desc: 'Memory hierarchy: Registers → Cache → RAM → Secondary Storage',
        options: ['CPU Registers', 'Cache', 'RAM', 'SSD'], answer: 'CPU Registers',
        hints: ['The faster the memory, the smaller and closer to the CPU it is.', 'Registers are built INSIDE the CPU itself — nothing is closer.'],
        explain: '<strong>Registers are fastest</strong> — built inside the CPU, accessed in a single clock cycle. Then Cache (L1/L2/L3), then RAM, then secondary storage (SSD/HDD). Speed and cost decrease as you move down the hierarchy.' },
    ]
  },

  // ── PHASE 9: TWO'S COMPLEMENT (PREMIUM) ─────────────────
  {
    id: 9, name: "TWO'S COMPLEMENT", sub: 'How computers represent negative numbers',
    color: '#0F766E', visual: 'canvas', circuit: 'binary',
    boards: ['AQA', 'OCR'],
    intro: {
      what: "<strong>Two's complement</strong> is the standard method computers use to represent negative numbers in binary. In two's complement, the most significant bit (MSB) has a negative place value. For 8-bit two's complement, the place values are: -128, 64, 32, 16, 8, 4, 2, 1.",
      how: "To negate a number using two's complement: <strong>Step 1:</strong> flip all bits (NOT). <strong>Step 2:</strong> add 1 to the result. This method means addition circuits work for both positive and negative numbers — no special subtraction hardware needed.",
      examples: [
        "🔢 <strong>+5 in 8-bit binary:</strong> 00000101",
        "🔢 <strong>To get -5:</strong> Flip bits → 11111010, then add 1 → <strong>11111011</strong>",
        "🔢 <strong>Read -5:</strong> -128+64+32+16+8+0+2+1 = -5 ✓",
        "📝 <strong>Exam tip:</strong> The range of 8-bit two's complement is <strong>-128 to +127</strong>. If the leftmost bit is 1, the number is negative.",
      ],
      tip: "💡 Two's complement trick: to find the negative of a binary number, work from RIGHT to LEFT — copy bits up to and including the first 1, then flip all remaining bits.",
      meta: "5 QUESTIONS — TWO'S COMPLEMENT + NEGATIVE BINARY",
    },
    questions: [
      { type: 'MC', badge: "TWO'S COMPLEMENT", board: 'AQA · OCR',
        title: 'In 8-bit two\'s complement, what is the range of values?',
        desc: 'The MSB has a place value of -128 in two\'s complement',
        options: ['-128 to +127', '-127 to +127', '-128 to +128', '0 to 255'], answer: '-128 to +127',
        hints: ['The MSB (leftmost) represents -128. All other bits ON gives +127.', 'Minimum: 10000000 = -128. Maximum: 01111111 = +127.'],
        explain: "<strong>8-bit two's complement range: -128 to +127.</strong> Minimum = 10000000 (-128). Maximum = 01111111 (+127). Note: 256 total values, but split asymmetrically due to zero being positive." },
      { type: 'MC', badge: "TWO'S COMPLEMENT", board: 'AQA · OCR',
        title: "What is the two's complement of 00000101 (+5)?",
        desc: "Step 1: flip all bits. Step 2: add 1",
        options: ['11111011', '11111010', '10000101', '11111100'], answer: '11111011',
        hints: ["Flip all bits of 00000101 first: what do you get?", 'After flipping: 11111010. Now add 1 to that.'],
        explain: "<strong>+5 = 00000101. Flip: 11111010. Add 1: 11111011.</strong> This represents -5. Check: -128+64+32+16+8+0+2+1 = -5 ✓. Two's complement is always flip then add 1." },
      { type: 'MC', badge: "TWO'S COMPLEMENT", board: 'AQA · OCR',
        title: 'In two\'s complement, how do you know a number is negative?',
        desc: 'There is a simple rule involving the most significant bit',
        options: ['The most significant bit (leftmost) is 1', 'The least significant bit is 1', 'The number has more 1s than 0s', 'The number cannot be divided by 2'], answer: 'The most significant bit (leftmost) is 1',
        hints: ['In two\'s complement, the leftmost bit has a NEGATIVE place value.', 'If the leftmost bit is 1, it contributes a large negative value, making the whole number negative.'],
        explain: "<strong>If the MSB (leftmost bit) = 1, the number is negative</strong> in two's complement. This is because the MSB has place value -128 (in 8-bit). If it's 1, the negative component dominates. Simple rule: leading 1 = negative." },
      { type: 'MC', badge: "TWO'S COMPLEMENT", board: 'AQA · OCR',
        title: "What is the denary value of two's complement 11111110?",
        desc: "Place values (left to right): -128, 64, 32, 16, 8, 4, 2, 1",
        options: ['-2', '254', '128', '-128'], answer: '-2',
        hints: ['The leftmost bit is -128. The rest are positive. Add them up.', 'Values of ON bits: -128+64+32+16+8+4+2 = ?'],
        explain: "<strong>11111110 = -128+64+32+16+8+4+2+0 = -2.</strong> Check using the shortcut: two's complement of 00000010 (+2) → flip to 11111101 → add 1 → 11111110 = -2 ✓" },
      { type: 'MC', badge: "TWO'S COMPLEMENT", board: 'AQA · OCR',
        title: "Why do computers use two's complement for negative numbers?",
        desc: "Think about what hardware advantage it provides",
        options: ["The same addition circuits work for both positive and negative numbers", "It uses less memory than other methods", "It's easier for humans to read", "It allows storage of larger numbers"], answer: "The same addition circuits work for both positive and negative numbers",
        hints: ["What would you need if you stored negatives differently — extra hardware?", "With two's complement, 5 + (-5) = 0 using the same binary adder circuit."],
        explain: "<strong>Two's complement means subtraction = addition of a negative.</strong> 5 + (-5) = 00000101 + 11111011 = 00000000 (ignoring overflow). CPUs don't need separate subtraction hardware — the ALU just adds. This is why two's complement is universal." },
    ]
  },

  // ── PHASE 10: DATA REPRESENTATION (PREMIUM) ─────────────
  {
    id: 10, name: 'DATA REPRESENTATION', sub: 'ASCII, Unicode, images, sound, and compression',
    color: '#6D28D9', visual: 'canvas', circuit: 'binary',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'Computers represent <strong>all data</strong> as binary — text, images, and sound included. <strong>ASCII</strong> maps characters to 7-bit numbers (A=65, a=97). <strong>Unicode</strong> extends this to over a million characters for global language support. Images are stored as grids of pixels, sound as sampled numbers.',
      how: '<strong>Compression</strong> reduces file size: <strong>Lossy</strong> (removes data permanently — JPEG, MP3) vs <strong>Lossless</strong> (recovers original perfectly — PNG, FLAC). Run-Length Encoding (RLE) is a lossless method often tested at GCSE.',
      examples: [
        '📝 <strong>ASCII:</strong> "A" = 65 = 01000001 in binary. "a" = 97 = 01100001 (lowercase = uppercase + 32)',
        '🌍 <strong>Unicode:</strong> UTF-8 is backward compatible with ASCII. Emoji like 😊 = U+1F60A',
        '🖼️ <strong>Image metadata:</strong> Colour depth (bits per pixel), Resolution (pixels per dimension)',
        '🔉 <strong>Sound:</strong> Sample rate (samples per second, Hz) × Bit depth = file quality and size',
      ],
      tip: '💡 File size formula: <strong>Images</strong> = width × height × colour depth (bits). <strong>Sound</strong> = sample rate × bit depth × duration (seconds). These calculations appear on AQA Paper 2.',
      meta: '5 QUESTIONS — ASCII · UNICODE · COMPRESSION · FILE SIZE',
    },
    questions: [
      { type: 'MC', badge: 'DATA', board: 'AQA · OCR · Eduqas',
        title: 'What is ASCII?',
        desc: 'A standard for representing text in binary',
        options: ['A 7-bit character encoding standard mapping characters to binary values', 'A type of image compression', 'A network protocol', 'A sorting algorithm'], answer: 'A 7-bit character encoding standard mapping characters to binary values',
        hints: ['ASCII stands for American Standard Code for Information Interchange.', 'It assigns a unique 7-bit number to each character — letters, digits, punctuation.'],
        explain: "<strong>ASCII (American Standard Code for Information Interchange)</strong> uses 7 bits to represent 128 characters (0–127). 'A'=65, 'a'=97, '0'=48. It's the foundation of text representation in computing." },
      { type: 'MC', badge: 'DATA', board: 'AQA · OCR · Eduqas',
        title: 'Why was Unicode developed to replace ASCII?',
        desc: 'Think about the limitations of 7-bit ASCII',
        options: ['ASCII only supports 128 characters — not enough for global languages', 'Unicode is faster to process', 'ASCII uses too much storage', 'Unicode is more secure'], answer: 'ASCII only supports 128 characters — not enough for global languages',
        hints: ['7 bits = 128 possible values. How many characters are in Arabic, Chinese, Hindi...?', 'Unicode supports over 1 million code points — enough for all world languages and emoji.'],
        explain: "<strong>ASCII's 128 characters</strong> only cover English. Unicode supports 1,000,000+ code points — every language, symbol, and emoji. UTF-8 is the most common Unicode encoding and is backward compatible with ASCII." },
      { type: 'MC', badge: 'COMPRESSION', board: 'AQA · OCR · Eduqas',
        title: 'What is the difference between lossy and lossless compression?',
        desc: 'Both reduce file size but in different ways',
        options: ['Lossy permanently removes data; lossless recovers the original file exactly', 'Lossy is better quality; lossless has lower quality', 'Lossy is for text; lossless is for images', 'Lossy is faster to decompress; lossless is slower always'], answer: 'Lossy permanently removes data; lossless recovers the original file exactly',
        hints: ['If you compress and decompress a JPEG multiple times, does it get worse?', 'Lossless compression is like a ZIP — you get the exact original back.'],
        explain: "<strong>Lossy compression</strong> (JPEG, MP3) permanently discards data — smaller file but quality degrades, especially with repeated compression. <strong>Lossless</strong> (PNG, FLAC, ZIP) reconstructs the original exactly. Critical 4-mark exam question — always explain both." },
      { type: 'MC', badge: 'DATA', board: 'AQA · OCR · Eduqas',
        title: 'An image is 100×100 pixels with a colour depth of 24 bits. What is its uncompressed file size?',
        desc: 'File size = width × height × colour depth',
        options: ['240,000 bits', '24,000 bits', '100,000 bits', '2,400 bits'], answer: '240,000 bits',
        hints: ['Multiply: pixels wide × pixels tall × bits per pixel', '100 × 100 = 10,000 pixels. Each pixel uses 24 bits.'],
        explain: '<strong>File size = 100 × 100 × 24 = 240,000 bits</strong> (= 30,000 bytes = ~29.3 KB). This formula (width × height × colour depth) appears on AQA Paper 2 almost every year. Convert to bytes by dividing by 8.' },
      { type: 'MC', badge: 'COMPRESSION', board: 'AQA · OCR · Eduqas',
        title: 'Which compression format is lossless?',
        desc: 'One of these preserves the original data perfectly',
        options: ['PNG', 'JPEG', 'MP3', 'MPEG'], answer: 'PNG',
        hints: ['JPEG is used for photos and is lossy. What is the main alternative image format?', 'PNG was specifically designed to replace GIF and provide lossless compression.'],
        explain: '<strong>PNG = lossless</strong> (Portable Network Graphics). JPEG = lossy (good for photos). MP3 = lossy (audio). MPEG = lossy (video). For text documents and images needing perfect quality (logos, icons), use lossless formats like PNG or ZIP.' },
    ]
  },
];
