// ============================================================
// content.js — all phase + question data.
//
// Pure data, no logic. Each phase has an intro lesson and a list
// of questions. Each question has a `type` ('MC' or 'BINARY')
// that the engine uses to pick the right question-type module.
//
// Adding a new question type later (e.g. 'CIRCUIT') means adding
// questions with that type here + a matching module under
// js/questions/ — nothing in the engine needs to change.
// ============================================================

export const PHASES = [

  // ── PHASE 1: BINARY BASICS (FREE) ───────────────────────
  {
    id: 1, name: 'BINARY BASICS', sub: 'The language of all computers',
    color: '#2563EB', visual: 'canvas', circuit: 'binary',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'Computers store everything as <strong>binary</strong> — sequences of 1s and 0s called <strong>bits</strong>. Each bit has a place value; reading from the right they double (1, 2, 4, 8, 16...), so written out left-to-right the place values are <strong>… 8, 4, 2, 1</strong>. To convert binary to denary (decimal), add up the place values where the bit is 1.',
      how: 'This is tested in <strong>every single GCSE Computer Science paper</strong> across AQA, OCR, and Eduqas. Expect to convert between binary, denary, and hexadecimal under exam conditions.',
      examples: [
        '🔢 Binary <strong>1010</strong> → place values 8,4,2,1 → 1×8 + 0×4 + 1×2 + 0×1 = <strong>10 in denary</strong>',
        '🔢 Denary <strong>13</strong> → 1×8 + 1×4 + 0×2 + 1×1 → binary <strong>1101</strong>',
        '📝 <strong>GCSE exam tip:</strong> Always write out the place value row (8,4,2,1) above your answer — examiners award marks for working.',
      ],
      tip: '💡 Place values go LEFT to RIGHT: 8, 4, 2, 1 (for 4 bits). The leftmost bit is the <strong>most significant bit (MSB)</strong>, the rightmost is the <strong>least significant bit (LSB)</strong>.',
      meta: '5 QUESTIONS — BINARY CONVERSION + MULTIPLE CHOICE',
    },
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 2,
        title: 'Explain why computers represent all data using binary.',
        markScheme: [
          'Computer hardware is built from transistors/switches that have two states (e.g. on/off, high/low voltage).',
          'These two states map directly onto the binary digits 1 and 0, so binary is reliable to store and process.',
        ],
        explain: 'Two clear points: the hardware has two states, and those states map to 1/0. Don’t just say "computers only understand 1s and 0s" — say why.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 3,
        title: 'State how many bits are in a nibble and a byte, and the largest denary value one byte can store.',
        markScheme: [
          'A nibble = 4 bits.',
          'A byte = 8 bits.',
          'One byte stores values 0 to 255 (2⁸ = 256 combinations, so the largest is 255).',
        ],
        explain: 'The 255 mark wants the value and ideally the reason (2⁸ = 256 values, 0–255).' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 3,
        title: 'Describe a method for converting a denary number into binary.',
        markScheme: [
          'Write out the binary place values (the powers of two).',
          'Find the largest place value that fits into the number, subtract it, then repeat with the remainder.',
          'Put a 1 under each place value used and a 0 under the rest to give the binary number.',
        ],
        explain: 'Examiners reward a clear, repeatable method — place values, subtract the largest that fits, repeat.' },
    ],
    // computational questions are GENERATED fresh each load (no fixed
    // answer to memorise) — see js/generators.js. Standard binary (MSB-left).
    questions: [
      { gen: 'binaryToDenary' },
      { gen: 'bitsValues' },
      { gen: 'denaryToBinary' },
      { gen: 'binaryToDenary' },
      { gen: 'denaryToBinary' },
    ]
  },

  // ── PHASE 2: LOGIC GATES (FREE) ─────────────────────────
  {
    id: 2, name: 'LOGIC GATES', sub: 'The decision-makers inside every CPU',
    color: '#7C3AED', visual: 'canvas', circuit: 'gate',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: '<strong>Logic gates</strong> process binary signals using boolean logic. They are the fundamental building blocks of all digital circuits. Your CPU contains billions of them. GCSE exams test you on gate symbols, truth tables, and simple circuit outputs.',
      how: 'You must know the four main gates: <strong>AND, OR, NOT, XOR</strong>. For each, know the symbol, the rule, and be able to complete a truth table. AQA and OCR both include logic gate diagrams in Paper 1.',
      examples: [
        '🔵 <strong>AND:</strong> Output = 1 only when BOTH inputs are 1 &nbsp;|&nbsp; (like a strict condition: A AND B must be true)',
        '🟢 <strong>OR:</strong> Output = 1 when AT LEAST ONE input is 1 &nbsp;|&nbsp; (generous: either A OR B is enough)',
        '🔴 <strong>NOT:</strong> Inverts the input &nbsp;|&nbsp; NOT 1 = 0, NOT 0 = 1',
        '🟡 <strong>XOR:</strong> Output = 1 only when inputs are DIFFERENT &nbsp;|&nbsp; 1 XOR 0 = 1, 1 XOR 1 = 0',
      ],
      tip: '💡 Exam trick: NAND = NOT AND (inverted AND). You can build ANY logic circuit from NAND gates alone — this appears in higher-tier questions.',
      meta: '7 QUESTIONS — TRUTH TABLES + BUILD-A-CIRCUIT',
    },
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 4,
        title: 'Describe the behaviour of an AND gate and an OR gate.',
        markScheme: [
          'An AND gate outputs 1 only when all of its inputs are 1.',
          'An AND gate outputs 0 in every other case.',
          'An OR gate outputs 1 when at least one input is 1.',
          'An OR gate outputs 0 only when all of its inputs are 0.',
        ],
        explain: 'Give the output for BOTH the true case and the false case of each gate — that is how the 4 marks split.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 2,
        title: 'A NOT gate is given an input of 1. State its output and explain what a NOT gate does.',
        markScheme: [
          'Output = 0.',
          'A NOT gate inverts (flips) its single input — 1 becomes 0 and 0 becomes 1.',
        ],
        explain: 'NOT has only one input. The explanation mark is for the idea of inverting/flipping.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 2,
        title: 'Explain the difference between an OR gate and an XOR gate.',
        markScheme: [
          'OR outputs 1 if at least one input is 1, including when both inputs are 1.',
          'XOR outputs 1 only when the inputs are different — it outputs 0 when both inputs are 1.',
        ],
        explain: 'The key contrast is the both-1s case: OR gives 1, XOR gives 0.' },
    ],
    // gate-output questions are GENERATED (random gate + inputs each load).
    questions: [
      { gen: 'logicGate' },
      { gen: 'logicGate' },
      { gen: 'logicGate' },
      { gen: 'logicGate' },
      { gen: 'logicGate' },
      { type: 'CIRCUIT', badge: 'BUILD CIRCUIT', board: 'AQA · OCR · Eduqas',
        title: 'Drag a gate into the slot so the output is 1.',
        desc: 'Inputs A = 1 and B = 1 feed one gate. Choose a gate that makes the output 1 — more than one works.',
        inputs: [{ id: 'A', value: 1 }, { id: 'B', value: 1 }],
        gates: [{ id: 'G1', in: ['A', 'B'] }],
        output: 'G1', target: 1, palette: ['AND', 'OR', 'XOR'],
        hints: ['With A = 1 and B = 1, which gates give 1?', 'AND(1,1) = 1 and OR(1,1) = 1, but XOR(1,1) = 0.'],
        explain: '<strong>Both AND and OR work here.</strong> AND(1,1)=1 and OR(1,1)=1, so either is a valid answer. XOR(1,1)=0 because the inputs are the same. A circuit can have more than one correct arrangement.' },
      { type: 'CIRCUIT', badge: 'BUILD CIRCUIT', board: 'AQA · OCR · Eduqas',
        title: 'Build a two-gate circuit so the final output is 1.',
        desc: 'Inputs A = 1, B = 0, C = 1. Gate 1 takes A and B; Gate 2 takes Gate 1’s output and C. Make the output 1.',
        inputs: [{ id: 'A', value: 1 }, { id: 'B', value: 0 }, { id: 'C', value: 1 }],
        gates: [{ id: 'G1', in: ['A', 'B'] }, { id: 'G2', in: ['G1', 'C'] }],
        output: 'G2', target: 1, palette: ['AND', 'OR', 'XOR'],
        hints: ['Work left to right: first decide Gate 1’s output from A = 1, B = 0.', 'e.g. OR(1,0) = 1, then AND(1, C=1) = 1. Other combinations also reach 1.'],
        explain: '<strong>One solution: Gate 1 = OR (1 OR 0 = 1), Gate 2 = AND (1 AND 1 = 1).</strong> Several other gate pairs also produce 1 — the simulator accepts any arrangement that hits the target. This is how real circuits chain gates together.' },
    ]
  },

  // ── PHASE 3: HEXADECIMAL (FREE) ─────────────────────────
  {
    id: 3, name: 'HEXADECIMAL', sub: 'Base 16 — the programmer\'s shorthand',
    color: '#059669', visual: 'canvas', circuit: 'binary',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: '<strong>Hexadecimal (hex)</strong> is base 16. It uses digits 0–9 then A–F (where A=10, B=11, C=12, D=13, E=14, F=15). One hex digit represents exactly 4 binary bits, making it a compact way to represent binary. GCSE exams expect you to convert between hex, binary, and denary.',
      how: 'Hex appears everywhere in computing: memory addresses (<code>0xFF3A</code>), colour codes (<code>#FF8800</code>), error codes. The <code>0x</code> prefix means "this number is hexadecimal".',
      examples: [
        '🔢 Hex <strong>A</strong> = 10 in denary &nbsp;|&nbsp; Hex <strong>F</strong> = 15 in denary',
        '🔢 Hex <strong>1F</strong> = 1×16 + 15×1 = <strong>31</strong> in denary',
        '🔢 Hex <strong>FF</strong> = 15×16 + 15×1 = <strong>255</strong> in denary (maximum value of one byte)',
        '📝 <strong>GCSE exam tip:</strong> Binary → Hex: split binary into groups of 4 bits, convert each group. e.g. 11110000 → 1111=F, 0000=0 → <strong>F0</strong>',
      ],
      tip: '💡 FF in hex = 255 in denary = 11111111 in binary. One byte always = 2 hex digits. Learn this — it comes up in almost every paper.',
      meta: '5 QUESTIONS — HEX CONVERSION + MULTIPLE CHOICE',
    },
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 2,
        title: 'Explain why programmers often use hexadecimal instead of binary.',
        markScheme: [
          'One hex digit represents exactly four binary bits (a nibble), so hex is much shorter than the equivalent binary.',
          'Shorter codes are easier for humans to read and write, which reduces mistakes.',
        ],
        explain: '"1 hex digit = 4 bits" is the headline fact; the second mark is the human-readability benefit.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 3,
        title: 'Describe how an 8-bit binary number is converted into hexadecimal.',
        markScheme: [
          'Split the 8 bits into two groups of four (two nibbles).',
          'Convert each nibble into its denary value (0 to 15).',
          'Write each value as a hex digit, where 10 to 15 become A to F, giving a two-digit hex number.',
        ],
        explain: 'Split into nibbles → convert each → letters for 10–15. Three clear steps, three marks.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 2,
        title: 'State the denary and binary values represented by the hexadecimal value FF.',
        markScheme: [
          'FF in denary = 255.',
          'FF in binary = 11111111.',
        ],
        explain: 'FF is the maximum value of a single byte — worth memorising as 255 / 11111111.' },
    ],
    // hex conversions are GENERATED; the "why hex" concept stays hand-authored.
    questions: [
      { gen: 'hexToDenary' },
      { gen: 'denaryToHex' },
      { gen: 'binaryToHex' },
      { type: 'MC', badge: 'HEX', board: 'AQA · OCR · Eduqas',
        title: 'Why do programmers use hexadecimal?',
        desc: 'Think about the relationship between hex and binary',
        options: ['One hex digit represents exactly 4 binary bits', 'It is easier to type than binary', 'Computers process hex faster', 'It uses less storage than binary'], answer: 'One hex digit represents exactly 4 binary bits',
        hints: ['How many values can 4 bits hold? How many values does one hex digit hold?', 'Both have exactly 16 possible values (0–15 / 0–F).'],
        explain: '<strong>1 hex digit = 4 bits = 16 values.</strong> This perfect correspondence means hex is a compact, human-readable shorthand for binary. FF is far easier to read than 11111111.' },
      { gen: 'hexToDenary' },
    ]
  },

  // ── PHASE 4: HEX COLOURS (FREE) ─────────────────────────
  {
    id: 4, name: 'HEX COLOURS', sub: 'How screens mix red, green, and blue light',
    color: '#DC2626', visual: 'swatch', circuit: null,
    boards: ['AQA', 'OCR'],
    intro: {
      what: 'Every colour on a screen is made by mixing <strong>Red, Green, and Blue (RGB)</strong> light. Each channel is stored as one byte (0–255), written as two hex digits. A full hex colour code like <code>#FF8800</code> contains 3 bytes: FF=red, 88=green, 00=blue.',
      how: 'The format is always <strong>#RRGGBB</strong>. 00 means that channel is off, FF means it\'s at maximum. Mixing all three channels at maximum gives white; all at 00 gives black.',
      examples: [
        '🔴 <code>#FF0000</code> → Red=255, Green=0, Blue=0 → <strong>pure red</strong>',
        '🟢 <code>#00FF00</code> → Red=0, Green=255, Blue=0 → <strong>pure green</strong>',
        '⚪ <code>#FFFFFF</code> → all channels at 255 → <strong>white</strong>',
        '⚫ <code>#000000</code> → all channels at 0 → <strong>black</strong>',
      ],
      tip: '💡 Red+Green light = Yellow (not brown — screens mix light, not paint!). Red+Blue = Magenta. Green+Blue = Cyan.',
      meta: '5 QUESTIONS — COLOUR IDENTIFICATION + HEX READING',
    },
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR', marks: 3,
        title: 'Explain how a colour is represented using a hexadecimal colour code such as #RRGGBB.',
        markScheme: [
          'The code is made of three pairs of hex digits — one pair each for the Red, Green and Blue channels.',
          'Each pair ranges from 00 to FF, giving that channel an intensity from 0 to 255.',
          'The three channel intensities are mixed (added) together to produce the final colour.',
        ],
        explain: 'Three ideas: three channels, each 0–255, mixed additively.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR', marks: 2,
        title: 'State the hex code for pure red and explain why it produces red.',
        markScheme: [
          'Pure red = #FF0000.',
          'The red channel is at maximum (FF = 255) while green and blue are both off (00).',
        ],
        explain: 'The explanation must reference the channel values, not just name the colour.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR', marks: 2,
        title: 'Calculate how many different colours a 24-bit (#RRGGBB) colour code can represent, and show your working.',
        markScheme: [
          'Each of the three channels has 256 possible values (8 bits each).',
          '256 × 256 × 256 = 16,777,216 colours (about 16.7 million).',
        ],
        explain: 'Working = 256 × 256 × 256; the value (≈16.7 million) earns the second mark.' },
    ],
    questions: [
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'What colour does #FF0000 represent?',
        desc: 'Format: #RRGGBB — Red, Green, Blue',
        options: ['Red', 'Green', 'Blue', 'White'], answer: 'Red',
        hints: ['The first two digits (FF) are the red channel.', 'Red=FF (255), Green=00, Blue=00 — only red is on.'],
        explain: '<strong>#FF0000: Red=FF(255), Green=00, Blue=00.</strong> Only the red channel is at maximum. This is pure red light.' },
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'What colour does #FFFF00 represent?',
        desc: 'Red and green channels are both at maximum',
        options: ['Yellow', 'Cyan', 'Purple', 'White'], answer: 'Yellow',
        hints: ['Red=FF, Green=FF, Blue=00. What do red and green light make?', 'On screens, red + green light = yellow (opposite to paint mixing).'],
        explain: '<strong>#FFFF00: Red=FF, Green=FF, Blue=00 → Yellow.</strong> This surprises many students — mixing red and green LIGHT gives yellow, not brown. Screens use additive colour mixing.' },
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'Which hex code produces pure blue?',
        desc: 'Only the blue channel should be at maximum (FF)',
        options: ['#0000FF', '#FF0000', '#00FF00', '#00FFFF'], answer: '#0000FF',
        hints: ['Format is #RRGGBB. Blue is the last two digits.', 'Red=00, Green=00, Blue=FF.'],
        explain: '<strong>#0000FF: Red=00, Green=00, Blue=FF(255).</strong> Only the blue channel is active. This is pure blue — commonly used for hyperlinks and UI elements.' },
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'How many different colours can be represented using #RRGGBB?',
        desc: 'Each channel is one byte (0–255)',
        options: ['16,777,216', '65,536', '256', '16,384'], answer: '16,777,216',
        hints: ['There are 3 channels, each with 256 possible values.', '256 × 256 × 256 = ?'],
        explain: '<strong>256 × 256 × 256 = 16,777,216</strong> (about 16.7 million) colours. This is called 24-bit colour (3 bytes = 24 bits). Higher-quality images use 32-bit (adds an alpha/transparency channel).' },
      { type: 'MC', badge: 'HEX COLOURS', board: 'AQA · OCR',
        title: 'What does #000000 represent?',
        desc: 'All three channels are set to zero',
        options: ['Black', 'White', 'Grey', 'Transparent'], answer: 'Black',
        hints: ['00 means the channel is completely OFF.', 'If all three light channels are off, what colour do you see?'],
        explain: '<strong>#000000 → Black.</strong> All channels at 0 means no light. Screens are black when pixels are off. Contrast with #FFFFFF (white) where all channels are at maximum.' },
    ]
  },

  // ── PHASE 5: NETWORKING (PREMIUM) ───────────────────────
  {
    id: 5, name: 'NETWORKING', sub: 'How computers communicate across the world',
    color: '#0891B2', visual: 'canvas', circuit: 'cpu',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'Networks allow computers to share data. The internet is a global network using <strong>TCP/IP</strong> protocols. Every device has a unique <strong>IP address</strong>, and <strong>DNS</strong> converts human-readable names into IP addresses. Data travels as <strong>packets</strong> routed by devices called <strong>routers</strong>.',
      how: 'GCSE networking questions test: network types (LAN/WAN), network topologies, protocols (HTTP, HTTPS, FTP, TCP, IP, DNS, SMTP), hardware (router, switch, NIC), and network security.',
      examples: [
        '📡 <strong>LAN</strong> (Local Area Network): Devices in one location e.g. school network',
        '🌐 <strong>WAN</strong> (Wide Area Network): Spans large geographic areas e.g. the internet',
        '📖 <strong>DNS:</strong> You type <code>bbc.co.uk</code> → DNS looks up → <code>151.101.0.81</code> → your browser connects',
        '📦 <strong>Packet:</strong> Data split into chunks with source/destination IP headers — like addressed envelopes',
      ],
      tip: '💡 Exam favourite: know the difference between a <strong>router</strong> (connects networks, uses IP addresses) and a <strong>switch</strong> (connects devices within a network, uses MAC addresses).',
      meta: '7 QUESTIONS — PACKET ROUTING + PROTOCOLS',
    },
    questions: [
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What does DNS stand for?',
        desc: 'DNS is described as the "phonebook of the internet"',
        options: ['Domain Name System', 'Data Network Server', 'Digital Node Switch', 'Direct Name Service'], answer: 'Domain Name System',
        hints: ['It converts website names into something computers understand.', 'Think: what does a phonebook do? DNS does the same for websites.'],
        explain: '<strong>DNS = Domain Name System.</strong> It translates domain names (bbc.co.uk) into IP addresses (151.101.0.81). Without DNS you\'d memorise IP addresses. This is a guaranteed 1-mark question on most papers.' },
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What is the difference between a LAN and a WAN?',
        desc: 'Two fundamental network types you must know',
        options: ['LAN covers a small area; WAN spans large geographic areas', 'LAN is wireless; WAN is wired', 'LAN uses TCP; WAN uses IP', 'LAN is faster than WAN always'], answer: 'LAN covers a small area; WAN spans large geographic areas',
        hints: ['LAN = Local Area Network. Where is "local"?', 'Think school vs the internet.'],
        explain: '<strong>LAN (Local Area Network)</strong> connects devices in one location (school, office). <strong>WAN (Wide Area Network)</strong> spans large areas — the internet is the largest WAN. A key 2-mark question on all boards.' },
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What is the role of a router?',
        desc: 'Routers are the traffic directors of the internet',
        options: ['Directs packets between different networks using IP addresses', 'Connects devices within a single network', 'Converts domain names to IP addresses', 'Encrypts data before transmission'], answer: 'Directs packets between different networks using IP addresses',
        hints: ['A router works with IP addresses and connects different networks together.', 'Compare: a switch connects devices WITHIN a network; a router connects NETWORKS to each other.'],
        explain: '<strong>Routers</strong> forward data packets between networks using IP addresses. Your home router connects your LAN to the internet (a WAN). Examiners often ask you to distinguish routers from switches.' },
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What does HTTP stand for?',
        desc: 'You see this protocol at the start of web addresses',
        options: ['HyperText Transfer Protocol', 'High Traffic Transfer Process', 'Home Terminal Text Program', 'Hyperlink Transport Tool Protocol'], answer: 'HyperText Transfer Protocol',
        hints: ['It\'s the protocol used to transfer web pages between servers and browsers.', 'The S in HTTPS stands for Secure — it adds encryption via TLS.'],
        explain: '<strong>HTTP = HyperText Transfer Protocol.</strong> The set of rules for transferring web pages. HTTPS adds TLS encryption (the padlock icon). Knowing common protocols (HTTP, FTP, SMTP, DNS) is essential for Paper 1.' },
      { type: 'MC', badge: 'NETWORKING', board: 'AQA · OCR · Eduqas',
        title: 'What is packet switching?',
        desc: 'The method used to transmit data across the internet',
        options: ['Breaking data into packets that travel independently and are reassembled at destination', 'Sending all data in one continuous stream', 'Encrypting data before transmission', 'Compressing files before sending'], answer: 'Breaking data into packets that travel independently and are reassembled at destination',
        hints: ['Think of sending a book torn into individual pages — each page finds its own route.', 'Packets can take different routes and arrive out of order, then be reassembled.'],
        explain: '<strong>Packet switching</strong> splits data into packets, each with header information (source/destination IP). Packets travel independently across the network and are reassembled. It\'s efficient because network capacity is shared.' },
      { type: 'PACKET', badge: 'PACKET SWITCHING', board: 'AQA · OCR · Eduqas',
        title: 'Route the packet from HOME to the SERVER.',
        desc: 'Click a connected router to hop the packet. One link is down (dashed red) — route around it before the hop budget runs out.',
        nodes: [
          { id: 'HOME', x: 0.10, y: 160, label: 'HOME' },
          { id: 'R1', x: 0.38, y: 80, label: 'R1' },
          { id: 'R2', x: 0.38, y: 250, label: 'R2' },
          { id: 'R3', x: 0.66, y: 160, label: 'R3' },
          { id: 'SERVER', x: 0.90, y: 160, label: 'SERVER' },
        ],
        links: [['HOME', 'R1'], ['HOME', 'R2'], ['R1', 'R3'], ['R2', 'R3'], ['R3', 'SERVER'], ['R1', 'SERVER'], ['R2', 'SERVER']],
        down: [['R1', 'SERVER']],
        source: 'HOME', dest: 'SERVER', ttl: 3,
        hints: ['The dashed R1–SERVER link is down — a packet cannot cross it.', 'HOME → R2 → SERVER reaches the destination in two hops.'],
        explain: '<strong>Packet switching</strong> routes packets independently and can take different paths. With the R1–SERVER link down, the network routes around the failure (e.g. HOME → R2 → SERVER). The <strong>TTL (time to live)</strong> is a hop limit that stops a lost packet circulating the network forever.' },
      { type: 'PACKET', badge: 'PACKET SWITCHING', board: 'AQA · OCR · Eduqas',
        title: 'Send the packet to the SERVER in as few hops as possible.',
        desc: 'Only 2 hops of TTL. Pick the shortest route — a wrong turn wastes the budget and the packet is dropped.',
        nodes: [
          { id: 'PC', x: 0.10, y: 160, label: 'PC' },
          { id: 'A', x: 0.42, y: 80, label: 'R-A' },
          { id: 'B', x: 0.42, y: 250, label: 'R-B' },
          { id: 'C', x: 0.70, y: 250, label: 'R-C' },
          { id: 'SERVER', x: 0.90, y: 160, label: 'SERVER' },
        ],
        links: [['PC', 'A'], ['PC', 'B'], ['A', 'SERVER'], ['B', 'C'], ['C', 'SERVER']],
        source: 'PC', dest: 'SERVER', ttl: 2,
        hints: ['Two hops only — which neighbour of PC connects straight to a router that reaches the SERVER?', 'PC → R-A → SERVER is two hops; PC → R-B → R-C → SERVER is three (too many).'],
        explain: '<strong>Efficient routing</strong> matters: PC → R-A → SERVER reaches the SERVER in 2 hops, while PC → R-B → R-C → SERVER takes 3. Routers use routing tables to forward each packet along the most efficient available path; the TTL caps how many hops a packet may waste.' },
    ],
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR', marks: 4,
        title: 'Explain the difference between a LAN and a WAN, and give an example of each.',
        markScheme: [
          'A LAN (Local Area Network) connects devices over a small geographical area (e.g. one site).',
          'A WAN (Wide Area Network) connects devices over a large geographical area.',
          'Example of a LAN: a school / office / home network.',
          'Example of a WAN: the internet.',
        ],
        explain: 'Exam tip: write each term in full at least once, and anchor every point with its example — the example is usually a separate mark.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 4,
        title: 'Describe how packet switching is used to send data across the internet.',
        markScheme: [
          'The data is split into packets.',
          'Each packet has a header containing the source and destination IP addresses (and a sequence number).',
          'Packets are routed independently and may take different paths across the network.',
          'Packets are reassembled into the original data, in the correct order, at the destination.',
        ],
        explain: 'A 4-mark "describe" wants four distinct stages: split → header/addressing → independent routing → reassembly.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 3,
        title: 'State what DNS stands for and describe what it does.',
        markScheme: [
          'DNS = Domain Name System.',
          'It translates (looks up) a domain name, e.g. bbc.co.uk, into its IP address.',
          'This lets the browser connect to the correct server without the user needing to know the IP address.',
        ],
        explain: 'The first mark is simply the correct expansion of the acronym; examiners accept "converts/translates domain names to IP addresses" for the function.' },
    ]
  },

  // ── PHASE 6: ALGORITHMS (PREMIUM) ───────────────────────
  {
    id: 6, name: 'ALGORITHMS', sub: 'Sorting, searching, and computational thinking',
    color: '#D97706', visual: 'sort', circuit: null,
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'An <strong>algorithm</strong> is a precise set of steps to solve a problem. GCSE Computer Science tests sorting algorithms (Bubble Sort, Merge Sort, Insertion Sort) and searching algorithms (Linear Search, Binary Search). You must trace through them step-by-step.',
      how: '<strong>Big O notation</strong> describes efficiency. O(n) = linear time, O(n²) = quadratic, O(log n) = logarithmic. Binary search (O(log n)) is much faster than linear search (O(n)) for large sorted datasets.',
      examples: [
        '🔄 <strong>Bubble Sort pass on [5,3,1,4]:</strong> Compare 5&3 → swap → [3,5,1,4] → compare 5&1 → swap → [3,1,5,4] → compare 5&4 → swap → [3,1,4,5]',
        '🔍 <strong>Binary Search for 7 in [1,3,5,7,9]:</strong> Check middle (5) → 7>5, look right → check (7) → found in 2 steps!',
        '📝 <strong>Exam tip:</strong> Bubble Sort needs n-1 passes for n items. Show ALL comparisons and swaps — each earns a mark.',
      ],
      tip: '💡 Binary Search requires the list to be <strong>sorted first</strong>. Linear Search works on unsorted lists but is slower. This distinction is a common exam trap.',
      meta: '7 QUESTIONS — BUBBLE-SORT TRACE + EFFICIENCY',
    },
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 4,
        title: 'Describe how a bubble sort sorts a list of numbers.',
        markScheme: [
          'It passes through the list comparing each pair of adjacent items.',
          'If a pair is in the wrong order, the two items are swapped.',
          'After each pass the largest remaining item moves to its correct end position.',
          'Passes repeat until a complete pass makes no swaps (the list is sorted).',
        ],
        explain: 'Compare adjacent → swap if needed → largest bubbles to the end → repeat until no swaps.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 3,
        title: 'Explain why a binary search is usually faster than a linear search, and state the condition a binary search requires.',
        markScheme: [
          'Binary search repeatedly halves the search space, so it checks far fewer items.',
          'A linear search may have to check every item one at a time.',
          'Binary search requires the list to be sorted first.',
        ],
        explain: 'Halving vs checking every item is the speed argument; the precondition (sorted list) is a guaranteed mark.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 2,
        title: 'State what is meant by an algorithm.',
        markScheme: [
          'A precise sequence of steps or instructions.',
          'That solves a problem or completes a specific task.',
        ],
        explain: 'Examiners want "step-by-step" and "to solve a problem" — a program is one implementation of an algorithm.' },
    ],
    // bubble-sort result + traces are GENERATED on a fresh random list each load.
    questions: [
      { gen: 'bubbleResult' },
      { gen: 'bubblePass' },
      { gen: 'bubblePass' },
      { type: 'MC', badge: 'ALGORITHM', board: 'AQA · OCR · Eduqas',
        title: 'Binary Search: finding 9 in [1, 3, 5, 7, 9, 11]. Which element is checked first?',
        desc: 'Binary Search always starts at the middle element',
        options: ['5', '7', '1', '9'], answer: '5',
        hints: ['Binary Search picks the middle element of the list first.', 'List has 6 items. Middle index = 6÷2 = item at position 3 (value 5, using 0-based) or position 3 (value 5 or 7 depending on convention).'],
        explain: '<strong>Binary Search</strong> starts at the middle: index 2 (0-based) = value 5. Since 9>5, search the right half [7,9,11]. Next check: 9. Found! Only 2 checks instead of 6 with linear search.' },
      { type: 'MC', badge: 'ALGORITHM', board: 'AQA · OCR · Eduqas',
        title: 'What is the time complexity of Binary Search?',
        desc: 'Big O notation describes how time grows with input size',
        options: ['O(log n)', 'O(n)', 'O(n²)', 'O(1)'], answer: 'O(log n)',
        hints: ['Binary Search halves the remaining items each step.', 'Doubling the list size only adds ONE more step to Binary Search.'],
        explain: '<strong>Binary Search = O(log n).</strong> Each step halves the search space. For 1 million items, it takes at most 20 steps. Linear search O(n) would take up to 1 million. This efficiency difference is a key exam concept.' },
      { type: 'MC', badge: 'ALGORITHM', board: 'AQA · OCR · Eduqas',
        title: 'Which sorting algorithm has O(n²) worst-case time complexity?',
        desc: 'Think about how many comparisons are made for n items',
        options: ['Bubble Sort', 'Binary Search', 'Merge Sort', 'Linear Search'], answer: 'Bubble Sort',
        hints: ['For n items, Bubble Sort does roughly n×n comparisons in the worst case.', 'Merge Sort is more efficient — it\'s O(n log n).'],
        explain: '<strong>Bubble Sort = O(n²).</strong> For 10 items: up to 100 comparisons. For 100 items: up to 10,000. This makes it impractical for large datasets. Merge Sort (O(n log n)) is much faster but harder to trace.' },
      { type: 'MC', badge: 'ALGORITHM', board: 'AQA · OCR · Eduqas',
        title: 'What is a key requirement for Binary Search to work?',
        desc: 'A precondition that must be true before the algorithm can run',
        options: ['The list must be sorted', 'The list must have an even number of items', 'All items must be unique', 'The list must contain numbers only'], answer: 'The list must be sorted',
        hints: ['Binary Search works by comparing target to the middle and going left or right. What assumption makes this work?', 'If the list is unsorted, going "right" when the target is larger doesn\'t guarantee anything.'],
        explain: '<strong>Binary Search requires a sorted list.</strong> Without sorting, you can\'t determine which half contains the target. This is a classic exam trap — students forget this precondition.' },
    ]
  },

  // ── PHASE 7: ENCRYPTION & SECURITY (PREMIUM) ────────────
  {
    id: 7, name: 'ENCRYPTION', sub: 'Keeping data safe in a connected world',
    color: '#BE185D', visual: 'canvas', circuit: 'cpu',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: '<strong>Encryption</strong> scrambles data so only the intended recipient can read it. GCSE Computer Science covers Caesar cipher, symmetric vs asymmetric encryption, and common cyber threats (malware, phishing, SQL injection).',
      how: 'Key exam topics: <strong>Caesar cipher</strong> (shift letters by a fixed amount), <strong>symmetric encryption</strong> (same key to encrypt and decrypt), <strong>asymmetric encryption</strong> (public key encrypts, private key decrypts), and why HTTPS uses both.',
      examples: [
        '🔑 <strong>Caesar cipher (shift 3):</strong> A→D, B→E, C→F. "CAT" → "FDW"',
        '🔒 <strong>Symmetric:</strong> One shared secret key — fast but key must be shared securely',
        '🗝️ <strong>Asymmetric:</strong> Public key (share freely) encrypts; Private key (keep secret) decrypts',
        '📝 <strong>Exam tip:</strong> HTTPS uses asymmetric encryption to share a symmetric key, then uses that symmetric key for the session (it\'s faster).',
      ],
      tip: '💡 Common threats: <strong>Malware</strong> (virus, ransomware, spyware), <strong>Phishing</strong> (fake emails tricking users), <strong>SQL injection</strong> (malicious database queries), <strong>DDoS</strong> (flooding a server to take it offline).',
      meta: '7 QUESTIONS — CIPHER WHEEL + CYBER SECURITY',
    },
    // Caesar questions are GENERATED (random letter/shift + random word to crack).
    questions: [
      { gen: 'caesarLetter' },
      { gen: 'caesarDecode' },
      { gen: 'caesarDecode' },
      { type: 'MC', badge: 'ENCRYPTION', board: 'AQA · OCR · Eduqas',
        title: 'What is the difference between symmetric and asymmetric encryption?',
        desc: 'Two fundamental types of modern encryption',
        options: ['Symmetric uses one shared key; asymmetric uses a public/private key pair', 'Symmetric is stronger; asymmetric is weaker', 'Symmetric uses more keys; asymmetric uses fewer', 'Symmetric is for files; asymmetric is for emails only'], answer: 'Symmetric uses one shared key; asymmetric uses a public/private key pair',
        hints: ['Symmetric = same key for both sides. Think "symmetrical" — both sides are the same.', 'Asymmetric uses two mathematically linked keys — public (share freely) and private (keep secret).'],
        explain: '<strong>Symmetric:</strong> one shared secret key (fast, used for bulk data). <strong>Asymmetric:</strong> public key encrypts, private key decrypts (slower, used for key exchange). HTTPS uses asymmetric to share a symmetric session key.' },
      { type: 'MC', badge: 'ENCRYPTION', board: 'AQA · OCR · Eduqas',
        title: 'What type of attack involves flooding a server with traffic to make it unavailable?',
        desc: 'This attack aims to deny service to legitimate users',
        options: ['DDoS (Distributed Denial of Service)', 'Phishing', 'SQL Injection', 'Brute Force'], answer: 'DDoS (Distributed Denial of Service)',
        hints: ['The attack "denies" users access to a service by overwhelming it.', 'DDoS = Distributed — it uses many computers (a botnet) to flood the target.'],
        explain: '<strong>DDoS (Distributed Denial of Service)</strong> floods a server with requests from many compromised computers (a botnet) until it crashes or becomes too slow. A common 2-mark exam question: describe the attack and its impact.' },
      { type: 'MC', badge: 'ENCRYPTION', board: 'AQA · OCR · Eduqas',
        title: 'What is phishing?',
        desc: 'One of the most common social engineering attacks',
        options: ['Tricking users into revealing personal data via fake emails or websites', 'Installing malware via USB drives', 'Flooding a network with traffic', 'Intercepting data packets on a network'], answer: 'Tricking users into revealing personal data via fake emails or websites',
        hints: ['It\'s named after "fishing" — dangling bait to trick victims.', 'The attack targets human behaviour, not technical vulnerabilities.'],
        explain: '<strong>Phishing</strong> uses fake emails or websites that mimic legitimate organisations (banks, HMRC) to steal passwords, card numbers, or personal data. It\'s a "social engineering" attack — exploiting human psychology rather than software flaws.' },
      { type: 'MC', badge: 'ENCRYPTION', board: 'AQA · OCR · Eduqas',
        title: 'What is SQL injection?',
        desc: 'A common attack on databases accessed via web forms',
        options: ['Inserting malicious SQL code into input fields to manipulate a database', 'A type of DDoS attack', 'Encrypting a database with ransomware', 'Stealing cookies from a browser'], answer: 'Inserting malicious SQL code into input fields to manipulate a database',
        hints: ['SQL is used to query databases. What if a user typed SQL commands into a login form?', 'Input: "admin\' OR 1=1 --" could bypass a login check entirely.'],
        explain: '<strong>SQL injection</strong> inserts SQL commands into user input fields (e.g. login forms). If input isn\'t sanitised, the database executes the injected command. Prevention: input validation and parameterised queries.' },
    ],
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 4,
        title: 'Explain the difference between symmetric and asymmetric encryption.',
        markScheme: [
          'Symmetric encryption uses a single, shared key to both encrypt and decrypt.',
          'Asymmetric encryption uses a key pair — a public key and a private key.',
          'In asymmetric, data encrypted with the public key can only be decrypted with the matching private key.',
          'Symmetric is faster, but the key must be shared securely; asymmetric solves the problem of secure key exchange.',
        ],
        explain: 'A strong answer contrasts both on the same axis (number of keys, who holds them, speed). One-key vs key-pair is the headline mark.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 4,
        title: 'Describe two methods an organisation could use to help keep its network secure.',
        markScheme: [
          'Encryption — scrambles data so that intercepted data cannot be understood.',
          'Firewall — filters incoming/outgoing traffic and blocks unauthorised access.',
          'Strong passwords / authentication / user access levels — limit who can access what.',
          'Anti-malware software, penetration testing or physical security (any other valid method, described).',
        ],
        explain: '"Describe two" = name the method (1 mark) and say what it does (1 mark), twice. A bare list of names caps at half marks.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 3,
        title: 'Explain what phishing is and give one way a user can reduce the risk of falling for it.',
        markScheme: [
          'Phishing uses fake emails, messages or websites that imitate a legitimate organisation.',
          'The aim is to trick the user into revealing personal data (passwords, bank details) or clicking a malicious link.',
          'Mitigation: don\'t click links in unexpected emails / check the sender address / staff training / spam filters (any valid).',
        ],
        explain: 'Phishing targets the human, not the software — that framing earns the definition mark even without the term "social engineering".' },
    ]
  },

  // ── PHASE 8: CPU & MEMORY (PREMIUM) ─────────────────────
  {
    id: 8, name: 'CPU & MEMORY', sub: 'Von Neumann architecture and the fetch-decode-execute cycle',
    color: '#4F46E5', visual: 'canvas', circuit: 'cpu',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'The <strong>CPU (Central Processing Unit)</strong> is the brain of a computer. It uses the <strong>fetch-decode-execute cycle</strong> to process instructions. The <strong>von Neumann architecture</strong> stores both programs and data in the same memory — the standard model for all modern computers.',
      how: 'Key components: <strong>ALU</strong> (does maths and logic), <strong>CU</strong> (Control Unit — directs operations), <strong>Registers</strong> (tiny, ultra-fast memory inside the CPU), <strong>Cache</strong> (fast memory near CPU), <strong>RAM</strong> (main memory), <strong>ROM</strong> (read-only, stores BIOS/firmware).',
      examples: [
        '🔁 <strong>Fetch:</strong> CU gets the next instruction from RAM (at address in Program Counter)',
        '🔁 <strong>Decode:</strong> CU interprets the instruction',
        '🔁 <strong>Execute:</strong> ALU or other component carries out the instruction',
        '📝 <strong>CPU performance factors:</strong> Clock speed (GHz), number of cores, cache size',
      ],
      tip: '💡 Exam trap: <strong>RAM is volatile</strong> (lost when power off). <strong>ROM is non-volatile</strong> (persists). RAM is read/write; ROM is read-only. These definitions appear on every paper.',
      meta: '7 QUESTIONS — FETCH-DECODE-EXECUTE + MEMORY',
    },
    questions: [
      { type: 'MC', badge: 'CPU', board: 'AQA · OCR · Eduqas',
        title: 'What does the ALU do?',
        desc: 'ALU is a key component of the CPU',
        options: ['Performs arithmetic and logical operations', 'Stores data permanently', 'Fetches instructions from memory', 'Connects the CPU to external devices'], answer: 'Performs arithmetic and logical operations',
        hints: ['ALU = Arithmetic Logic Unit. The clue is in the name.', 'It handles: addition, subtraction, comparisons, AND, OR, NOT operations.'],
        explain: '<strong>ALU (Arithmetic Logic Unit)</strong> performs all maths (add, subtract, multiply) and logic operations (AND, OR, NOT, compare). It\'s built from the logic gates in Phase 2. Every calculation in every program goes through the ALU.' },
      { type: 'MC', badge: 'CPU', board: 'AQA · OCR · Eduqas',
        title: 'What is the fetch-decode-execute cycle?',
        desc: 'The fundamental repeating process of every CPU',
        options: ['Fetch instruction from memory, decode it, execute it — repeated continuously', 'Store, compress, and transmit data', 'Read, write, and delete files', 'Boot, load, and run an operating system'], answer: 'Fetch instruction from memory, decode it, execute it — repeated continuously',
        hints: ['Three stages, in order: get the instruction, understand it, carry it out.', 'The Program Counter (PC) register tracks which instruction to fetch next.'],
        explain: '<strong>Fetch-Decode-Execute:</strong> The CPU fetches the instruction at the address in the Program Counter, decodes what operation it means, then executes it. This cycle runs billions of times per second and is tested on every GCSE paper.' },
      { type: 'FDE', badge: 'CPU CYCLE', board: 'AQA · OCR · Eduqas',
        title: 'Trace the fetch–decode–execute cycle through the CPU.',
        desc: 'At each step the source register glows — click the component the data moves to. Follow it from fetch through to execute.',
        steps: [
          { stage: 'FETCH', from: 'PC', answer: 'MAR', prompt: 'The address in the Program Counter is copied to which register?' },
          { stage: 'FETCH', from: 'RAM', answer: 'MDR', prompt: 'The instruction at that address is fetched from RAM into which register?' },
          { stage: 'FETCH', from: 'MDR', answer: 'CIR', prompt: 'The fetched instruction is copied from the MDR into which register?' },
          { stage: 'FETCH', from: 'PC', answer: 'PC', prompt: 'Which register is then incremented to point at the next instruction?', note: 'PC + 1' },
          { stage: 'DECODE', from: 'CIR', answer: 'CU', prompt: 'Which unit decodes the instruction held in the CIR?' },
          { stage: 'EXECUTE', from: 'CU', answer: 'ALU', prompt: 'Which unit carries out an arithmetic or logic instruction?' },
        ],
        hints: ['Fetch order: PC → MAR, then the instruction returns into the MDR, then into the CIR.', 'After fetching, the PC is incremented; then the CU decodes and the ALU executes.'],
        explain: '<strong>Fetch:</strong> PC→MAR, RAM→MDR, MDR→CIR, then PC is incremented. <strong>Decode:</strong> the Control Unit interprets the instruction in the CIR. <strong>Execute:</strong> the ALU carries out arithmetic/logic. This cycle repeats billions of times a second — being able to trace it earns marks on every board.' },
      { type: 'FDE', badge: 'CPU CYCLE', board: 'AQA · OCR · Eduqas',
        title: 'Trace just the FETCH stage of the cycle.',
        desc: 'Four steps. At each one, click the component the data moves to.',
        steps: [
          { stage: 'FETCH', from: 'PC', answer: 'MAR', prompt: 'The address in the Program Counter goes to which register first?' },
          { stage: 'FETCH', from: 'RAM', answer: 'MDR', prompt: 'The instruction is read from RAM into which register?' },
          { stage: 'FETCH', from: 'MDR', answer: 'CIR', prompt: 'It is then copied from the MDR into which register?' },
          { stage: 'FETCH', from: 'PC', answer: 'PC', prompt: 'Finally, which register is incremented ready for the next instruction?', note: 'PC + 1' },
        ],
        hints: ['The MAR holds the ADDRESS; the MDR holds the DATA/instruction.', 'PC → MAR → (RAM) → MDR → CIR, then increment the PC.'],
        explain: '<strong>Fetch:</strong> the address in the PC is placed in the MAR; the instruction at that address is read from RAM into the MDR; it is copied into the CIR; and the PC is incremented so the next cycle fetches the following instruction.' },
      { type: 'MC', badge: 'MEMORY', board: 'AQA · OCR · Eduqas',
        title: 'What is the key difference between RAM and ROM?',
        desc: 'Both are types of primary storage inside a computer',
        options: ['RAM is volatile (lost when power off); ROM is non-volatile (persists)', 'RAM is faster than ROM', 'RAM stores the OS; ROM stores user files', 'RAM is read-only; ROM is read/write'], answer: 'RAM is volatile (lost when power off); ROM is non-volatile (persists)',
        hints: ['Volatile = data is lost when the power is cut. Which one clears when you turn off your computer?', 'ROM stores the BIOS/firmware that runs when you first switch on — it must survive power loss.'],
        explain: '<strong>RAM = volatile, read/write.</strong> Data is lost when power is removed. Used for running programs. <strong>ROM = non-volatile, read-only.</strong> Stores firmware/BIOS. Persists without power. A classic 2-mark question: state and explain the difference.' },
      { type: 'MC', badge: 'CPU', board: 'AQA · OCR · Eduqas',
        title: 'Which factor does NOT directly affect CPU performance?',
        desc: 'Know what actually determines how fast a CPU runs',
        options: ['The colour of the computer case', 'Clock speed (GHz)', 'Number of cores', 'Cache size'], answer: 'The colour of the computer case',
        hints: ['Think about what physically affects how fast the processor runs.', 'Clock speed, cores, and cache all have a direct technical impact on performance.'],
        explain: '<strong>CPU performance is affected by:</strong> Clock speed (how many cycles per second), Number of cores (parallel processing), Cache size (faster access to frequently used data). The case colour has zero effect — a common "odd one out" question.' },
      { type: 'MC', badge: 'MEMORY', board: 'AQA · OCR · Eduqas',
        title: 'In the memory hierarchy, which type of memory is fastest?',
        desc: 'Memory hierarchy: Registers → Cache → RAM → Secondary Storage',
        options: ['CPU Registers', 'Cache', 'RAM', 'SSD'], answer: 'CPU Registers',
        hints: ['The faster the memory, the smaller and closer to the CPU it is.', 'Registers are built INSIDE the CPU itself — nothing is closer.'],
        explain: '<strong>Registers are fastest</strong> — built inside the CPU, accessed in a single clock cycle. Then Cache (L1/L2/L3), then RAM, then secondary storage (SSD/HDD). Speed and cost decrease as you move down the hierarchy.' },
    ],
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 4,
        title: 'Describe the role of the Program Counter (PC) and the Memory Address Register (MAR) in the fetch–decode–execute cycle.',
        markScheme: [
          'The PC holds the address of the next instruction to be fetched.',
          'The PC is incremented during each cycle so it points to the following instruction.',
          'The MAR holds the address of the memory location to be read from or written to.',
          'At the start of the fetch, the address in the PC is copied into the MAR.',
        ],
        explain: 'Keep the two registers separate: PC = which instruction is next; MAR = which memory address we are about to access.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 4,
        title: 'Explain two differences between RAM and ROM.',
        markScheme: [
          'RAM is volatile (loses its contents when power is removed); ROM is non-volatile (keeps its contents).',
          'RAM can be read from and written to; ROM is read-only (cannot normally be written to).',
          'RAM stores currently-running programs and data; ROM stores the boot/firmware (e.g. the BIOS).',
          'RAM is typically much larger in capacity than ROM.',
        ],
        explain: 'Each difference must compare BOTH parts on the same property (e.g. "RAM is volatile whereas ROM is non-volatile") to earn the pair of marks.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 4,
        title: 'State three factors that affect CPU performance, and briefly explain how one of them does so.',
        markScheme: [
          'Clock speed — the number of fetch–execute cycles per second (higher = more instructions per second).',
          'Number of cores — more cores can process more instructions simultaneously.',
          'Cache size — a larger cache keeps more frequently-used data close to the CPU, reducing slower fetches from RAM.',
          'A correct brief explanation of any one named factor (the explanation mark).',
        ],
        explain: 'Three named factors = 3 marks; the 4th is the explanation. Don\'t spend all your effort naming — leave a sentence to explain one.' },
    ]
  },

  // ── PHASE 9: TWO'S COMPLEMENT (PREMIUM) ─────────────────
  {
    id: 9, name: "TWO'S COMPLEMENT", sub: 'How computers represent negative numbers',
    color: '#0F766E', visual: 'canvas', circuit: 'binary',
    boards: ['AQA', 'OCR'],
    intro: {
      what: "<strong>Two's complement</strong> is the standard method computers use to represent negative numbers in binary. In two's complement, the most significant bit (MSB) has a negative place value. For 8-bit two's complement, the place values are: -128, 64, 32, 16, 8, 4, 2, 1.",
      how: "To negate a number using two's complement: <strong>Step 1:</strong> flip all bits (NOT). <strong>Step 2:</strong> add 1 to the result. This method means addition circuits work for both positive and negative numbers — no special subtraction hardware needed.",
      examples: [
        "🔢 <strong>+5 in 8-bit binary:</strong> 00000101",
        "🔢 <strong>To get -5:</strong> Flip bits → 11111010, then add 1 → <strong>11111011</strong>",
        "🔢 <strong>Read -5:</strong> -128+64+32+16+8+0+2+1 = -5 ✓",
        "📝 <strong>Exam tip:</strong> The range of 8-bit two's complement is <strong>-128 to +127</strong>. If the leftmost bit is 1, the number is negative.",
      ],
      tip: "💡 Two's complement trick: to find the negative of a binary number, work from RIGHT to LEFT — copy bits up to and including the first 1, then flip all remaining bits.",
      meta: "5 QUESTIONS — TWO'S COMPLEMENT + NEGATIVE BINARY",
    },
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR', marks: 3,
        title: 'Explain how two’s complement is used to represent a negative number in binary.',
        markScheme: [
          'In two’s complement the most significant (leftmost) bit has a negative place value (e.g. -128 in 8-bit).',
          'A number is negative when that most significant bit is 1.',
          'To get a negative value you flip all the bits of the positive number and then add 1.',
        ],
        explain: 'MSB is negative → a leading 1 means negative → "flip the bits and add 1" to negate.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR', marks: 2,
        title: 'State the range of values that can be stored using 8-bit two’s complement.',
        markScheme: [
          'Minimum value = -128.',
          'Maximum value = +127.',
        ],
        explain: 'Range is -128 to +127 (256 values, but not symmetric because 0 counts as positive).' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR', marks: 2,
        title: 'Explain one advantage of using two’s complement to store negative numbers.',
        markScheme: [
          'The same binary addition circuit works for both positive and negative numbers.',
          'So subtraction can be performed by adding a negative — no separate subtraction hardware is needed.',
        ],
        explain: 'The hardware-simplicity point is the expected answer: one adder handles both add and subtract.' },
    ],
    questions: [
      { type: 'MC', badge: "TWO'S COMPLEMENT", board: 'AQA · OCR',
        title: 'In 8-bit two\'s complement, what is the range of values?',
        desc: 'The MSB has a place value of -128 in two\'s complement',
        options: ['-128 to +127', '-127 to +127', '-128 to +128', '0 to 255'], answer: '-128 to +127',
        hints: ['The MSB (leftmost) represents -128. All other bits ON gives +127.', 'Minimum: 10000000 = -128. Maximum: 01111111 = +127.'],
        explain: "<strong>8-bit two's complement range: -128 to +127.</strong> Minimum = 10000000 (-128). Maximum = 01111111 (+127). Note: 256 total values, but split asymmetrically due to zero being positive." },
      { gen: 'twosNegate' },
      { type: 'MC', badge: "TWO'S COMPLEMENT", board: 'AQA · OCR',
        title: 'In two\'s complement, how do you know a number is negative?',
        desc: 'There is a simple rule involving the most significant bit',
        options: ['The most significant bit (leftmost) is 1', 'The least significant bit is 1', 'The number has more 1s than 0s', 'The number cannot be divided by 2'], answer: 'The most significant bit (leftmost) is 1',
        hints: ['In two\'s complement, the leftmost bit has a NEGATIVE place value.', 'If the leftmost bit is 1, it contributes a large negative value, making the whole number negative.'],
        explain: "<strong>If the MSB (leftmost bit) = 1, the number is negative</strong> in two's complement. This is because the MSB has place value -128 (in 8-bit). If it's 1, the negative component dominates. Simple rule: leading 1 = negative." },
      { gen: 'twosToDenary' },
      { type: 'MC', badge: "TWO'S COMPLEMENT", board: 'AQA · OCR',
        title: "Why do computers use two's complement for negative numbers?",
        desc: "Think about what hardware advantage it provides",
        options: ["The same addition circuits work for both positive and negative numbers", "It uses less memory than other methods", "It's easier for humans to read", "It allows storage of larger numbers"], answer: "The same addition circuits work for both positive and negative numbers",
        hints: ["What would you need if you stored negatives differently — extra hardware?", "With two's complement, 5 + (-5) = 0 using the same binary adder circuit."],
        explain: "<strong>Two's complement means subtraction = addition of a negative.</strong> 5 + (-5) = 00000101 + 11111011 = 00000000 (ignoring overflow). CPUs don't need separate subtraction hardware — the ALU just adds. This is why two's complement is universal." },
    ]
  },

  // ── PHASE 10: DATA REPRESENTATION (PREMIUM) ─────────────
  {
    id: 10, name: 'DATA REPRESENTATION', sub: 'ASCII, Unicode, images, sound, and compression',
    color: '#6D28D9', visual: 'canvas', circuit: 'binary',
    boards: ['AQA', 'OCR', 'Eduqas'],
    intro: {
      what: 'Computers represent <strong>all data</strong> as binary — text, images, and sound included. <strong>ASCII</strong> maps characters to 7-bit numbers (A=65, a=97). <strong>Unicode</strong> extends this to over a million characters for global language support. Images are stored as grids of pixels, sound as sampled numbers.',
      how: '<strong>Compression</strong> reduces file size: <strong>Lossy</strong> (removes data permanently — JPEG, MP3) vs <strong>Lossless</strong> (recovers original perfectly — PNG, FLAC). Run-Length Encoding (RLE) is a lossless method often tested at GCSE.',
      examples: [
        '📝 <strong>ASCII:</strong> "A" = 65 = 01000001 in binary. "a" = 97 = 01100001 (lowercase = uppercase + 32)',
        '🌍 <strong>Unicode:</strong> UTF-8 is backward compatible with ASCII. Emoji like 😊 = U+1F60A',
        '🖼️ <strong>Image metadata:</strong> Colour depth (bits per pixel), Resolution (pixels per dimension)',
        '🔉 <strong>Sound:</strong> Sample rate (samples per second, Hz) × Bit depth = file quality and size',
      ],
      tip: '💡 File size formula: <strong>Images</strong> = width × height × colour depth (bits). <strong>Sound</strong> = sample rate × bit depth × duration (seconds). These calculations appear on AQA Paper 2.',
      meta: '5 QUESTIONS — ASCII · UNICODE · COMPRESSION · FILE SIZE',
    },
    paper: [
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 4,
        title: 'Explain the difference between lossy and lossless compression.',
        markScheme: [
          'Lossy compression permanently removes some of the data to reduce the file size.',
          'The original file cannot be recovered exactly and quality can drop (e.g. JPEG, MP3).',
          'Lossless compression reduces the file size without discarding any data.',
          'The original file can be reconstructed exactly (e.g. PNG, FLAC, ZIP).',
        ],
        explain: 'Each type needs what it does to the data AND whether the original can be recovered. Examples help secure the marks.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 2,
        title: 'Explain why Unicode was developed when ASCII already existed.',
        markScheme: [
          'ASCII uses 7 bits, so it can only represent 128 characters — enough for English but not other languages.',
          'Unicode uses more bits to represent over a million characters, covering the world’s languages and emoji.',
        ],
        explain: 'The limitation of ASCII (128 characters) drives the need; Unicode’s large character set is the fix.' },
      { type: 'EXAM', badge: 'EXAM', board: 'AQA · OCR · Eduqas', marks: 3,
        title: 'An image is 200 pixels wide and 100 pixels high with a colour depth of 3 bits. Calculate its uncompressed file size in bits, showing your method.',
        markScheme: [
          'File size (bits) = width × height × colour depth.',
          '= 200 × 100 × 3.',
          '= 60,000 bits.',
        ],
        explain: 'Always quote the formula (width × height × colour depth) for a method mark, then substitute and evaluate.' },
    ],
    questions: [
      { type: 'MC', badge: 'DATA', board: 'AQA · OCR · Eduqas',
        title: 'What is ASCII?',
        desc: 'A standard for representing text in binary',
        options: ['A 7-bit character encoding standard mapping characters to binary values', 'A type of image compression', 'A network protocol', 'A sorting algorithm'], answer: 'A 7-bit character encoding standard mapping characters to binary values',
        hints: ['ASCII stands for American Standard Code for Information Interchange.', 'It assigns a unique 7-bit number to each character — letters, digits, punctuation.'],
        explain: "<strong>ASCII (American Standard Code for Information Interchange)</strong> uses 7 bits to represent 128 characters (0–127). 'A'=65, 'a'=97, '0'=48. It's the foundation of text representation in computing." },
      { type: 'MC', badge: 'DATA', board: 'AQA · OCR · Eduqas',
        title: 'Why was Unicode developed to replace ASCII?',
        desc: 'Think about the limitations of 7-bit ASCII',
        options: ['ASCII only supports 128 characters — not enough for global languages', 'Unicode is faster to process', 'ASCII uses too much storage', 'Unicode is more secure'], answer: 'ASCII only supports 128 characters — not enough for global languages',
        hints: ['7 bits = 128 possible values. How many characters are in Arabic, Chinese, Hindi...?', 'Unicode supports over 1 million code points — enough for all world languages and emoji.'],
        explain: "<strong>ASCII's 128 characters</strong> only cover English. Unicode supports 1,000,000+ code points — every language, symbol, and emoji. UTF-8 is the most common Unicode encoding and is backward compatible with ASCII." },
      { type: 'MC', badge: 'COMPRESSION', board: 'AQA · OCR · Eduqas',
        title: 'What is the difference between lossy and lossless compression?',
        desc: 'Both reduce file size but in different ways',
        options: ['Lossy permanently removes data; lossless recovers the original file exactly', 'Lossy is better quality; lossless has lower quality', 'Lossy is for text; lossless is for images', 'Lossy is faster to decompress; lossless is slower always'], answer: 'Lossy permanently removes data; lossless recovers the original file exactly',
        hints: ['If you compress and decompress a JPEG multiple times, does it get worse?', 'Lossless compression is like a ZIP — you get the exact original back.'],
        explain: "<strong>Lossy compression</strong> (JPEG, MP3) permanently discards data — smaller file but quality degrades, especially with repeated compression. <strong>Lossless</strong> (PNG, FLAC, ZIP) reconstructs the original exactly. Critical 4-mark exam question — always explain both." },
      { gen: 'fileSizeImage' },
      { type: 'MC', badge: 'COMPRESSION', board: 'AQA · OCR · Eduqas',
        title: 'Which compression format is lossless?',
        desc: 'One of these preserves the original data perfectly',
        options: ['PNG', 'JPEG', 'MP3', 'MPEG'], answer: 'PNG',
        hints: ['JPEG is used for photos and is lossy. What is the main alternative image format?', 'PNG was specifically designed to replace GIF and provide lossless compression.'],
        explain: '<strong>PNG = lossless</strong> (Portable Network Graphics). JPEG = lossy (good for photos). MP3 = lossy (audio). MPEG = lossy (video). For text documents and images needing perfect quality (logos, icons), use lossless formats like PNG or ZIP.' },
    ]
  },
];
